### ISSUE TITLE
zsh support, including option descriptions

### ISSUE THREAD

**Issue by nickl-** [kislyuk/argcomplete#10]
Let me start by saying well done with all the improvements since v2.9 the README looks awesome I must make a point to look at the docs... but who reads manuals anyway? =)

Being the devils advocate again,  even though I am well aware that the project clearly states **BASH** completion I know there are many who use `zsh` for whatever reasons unbeknown to myself, your friendly devil and scope-boundary-shifter extraordinaire.

From what I can source the differences are not that huge but I am not well versed on things that make you go `Oh My` at all, maybe someone with such astonishment afflictions would care to step up and explain yourselves or just enlighten us on the peculiarities of zsh completion as both would be fascinating to hear.

What I can add: There is something called `bashcompinit` as explained in [`man zshcompsys`](http://linux.die.net/man/1/zshcompsys)  and reads as follows:

> The function bashcompinit compatibility with bash's programmable completion system. When run it will define the functions, compgen and complete which correspond to the bash builtins with the same names. It will then be possible to use completion specifications and functions written for bash.

Would that suggest our work is done here or do we need something other (`zstyle`, `compctl`, worshiping of false devils perhaps)? None of which would make me jump with joy, being a jealous devil and all, just thought I'd stir the pot and see what's cooking.

nJoy!

**Comment by yac** [comment]
FYI: I tested with zsh's `bashcompinit` and it indeed seems to work fine.

As already stated, bash completion is overly simple (read: crap) and using zsh native completion would yield much better results... However, supporting multiple output formats in a code that was written with only one in mind sounds like more work than I'm willing to do. But a man can dream, right? :)

**Comment by segevfiner** [comment]
If completion doesn't work for you using `bashcompinit`, note https://github.com/zsh-users/zsh/commit/e2f793e7df7214cc3d80e2fcfe961ed087c860ab which I add to apply to my system's `bashcompinit` to get this to work.

**Comment by atyshka** [comment]
Will global support work in zsh the same way it does in bash? I.e. not having to individually register files? The portion of the README addressing zsh only describes the individual file method.

**Comment by dan1994** [comment]
When switching to `zsh` and finding out that `argcomplete` is not fully compatible (via this issue), I decided to try my hand at writing my own solution to this problem.
I have just released my first version of it, and thought to share for all of the people who'll reach this thread like I did.
The project is called `pyzshcomplete` and can be found [here](https://pypi.org/project/pyzshcomplete/). 
Any feedback would be highly appreciated.

**Comment by kislyuk** [comment]
argcomplete now supports zsh directly (without the bashcompinit compatibility layer) in the develop branch.

The practical impact of this support is currently limited to emitting description strings in zsh, but by directly emitting completions to zsh instead of using the bash compatibility layer, we have unlocked the potential for using other, fancier zsh features as well.

Global completion is not supported yet (I am still looking into how to support it in zsh), so commands have to be individually registered with register-python-argcomplete.

I will be releasing this functionality in a new release shortly.

**Comment by kislyuk** [comment]
OK, I was able to activate global completion for zsh using `compdef _python_argcomplete_global -P '*'`, so zsh is now fully and officially supported by argcomplete.

**Comment by kislyuk** [comment]
Released in v3.0.0.
