### ISSUE TITLE
Forward slash is not added when autocompleting

### ISSUE THREAD

**Issue by gerardo-garcia** [kislyuk/argcomplete#100]
When trying to autocomplete with a file in the filesystem, the forward slash of the directories is not added (by the way, I'm using Linux). Example:

program node-create /home/user/nod
<TAB>
program node-create /home/user/nodes

I was expecting:
program node-create /home/user/nod
<TAB>
program node-create /home/user/nodes/

I am using argcomplete and argparse in a code that creates a main parser and several subparsers as follows:

main_parser = argparse.ArgumentParser(description='Test program')
main_parser.add_argument('--version', action='version', version='%(prog)s ' + version )
subparsers = main_parser.add_subparsers(help='commands')
config_parser = subparsers.add_parser('config', help="prints configuration values")
config_parser.set_defaults(func=config)
node_create_parser = subparsers.add_parser('node-create', help="adds a node into the catalogue")
node_create_parser.add_argument("file", action="store", help="location of the file describing the node")
node_create_parser.set_defaults(func=node_create)
node_list_parser = subparsers.add_parser('node-list', help="lists information about a node")
node_list_parser.add_argument("name", nargs='?', help="name of the node")

argcomplete.autocomplete(main_parser)
args = main_parser.parse_args()
args.func(args)

**Comment by kislyuk** [comment]
You're not specifying a completer for your option. Please take a look at
the docs and set a completer. A filename completer is available in
argcomplete.completers.

**Comment by gerardo-garcia** [comment]
You're totally right. I have just added and it works as expected.
However, when I add that completer, I don't see optional arguments.

Code:
node_create_parser = subparsers.add_parser('node-create', help="adds a node into the catalogue")
node_create_parser.add_argument("file", action="store", help="location of the file describing the node").completer = FilesCompleter
node_create_parser.add_argument("--description", action="store", help="description of the node)
node_create_parser.set_defaults(func=node_create)

Execution:
program node-create
TAB
nodes/   temp/

I was expecting:
program node-create
TAB
nodes/   temp/   -h   --description

**Comment by kislyuk** [comment]
That's a good point, I'll see if I can figure out how to make the optionals show up.

**Comment by brookskindle** [comment]
Glad I found this issue, solved my problem too!

I tried [searching the docs](https://argcomplete.readthedocs.org/en/latest/search.html?q=FilesCompleter&check_keywords=yes&area=default#) and nothing came up for `FilesCompleter`

If this is a common enough case, perhaps it merits a section in the main README?
