### ISSUE TITLE
Use of python-argcomplete-check-easy-install-script

### ISSUE THREAD

**Issue by gar1t** [kislyuk/argcomplete#101]
I'm using python-argcomplete-check-easy-install-script to check if a setup.py (distutils) script wrapper will work. I'm getting this result: 

```
pkg_resources.DistributionNotFound: dna==0.0.0
```

Here's the wrapper script:

``` python
#!/opt/dna/bin/python
# EASY-INSTALL-SCRIPT: 'dna==0.0.0','dna'
__requires__ = 'dna==0.0.0'
import pkg_resources
pkg_resources.run_script('dna==0.0.0', 'dna')
```

One possible hitch is that I'm using virtualenv.py to install the Python runtime under /opt/dna.

More broadly though - how might I approach debugging this problem?

**Comment by kislyuk** [comment]
This typically indicates that the interpreter running `python-argcomplete-check-easy-install-script` is not the same interpreter as what the wrapper script would be run with. More precisely, it could be the same interpreter, but configured with a different `sys.path` in its startup configuration.

Does the result differ when you run the script after activating the virtualenv vs. when the virtualenv is deactivated?

**Comment by VorpalBlade** [comment]
I have observed this issue as well (using the global completion feature), when python-argcomplete-check-easy-install-script ended up running in Python 2, and the script with argument completion was a Python 3 script. Since the two Python versions have different packages installed there appears to be no way to get global completion to work for both versions. As I have both Python 2-only and Python 3-only scripts that need argument-completion in my environment this is quite a big issue in my case.
Possibly python-argcomplete-check-easy-install-script could look at the #! line of the wrapper to detect which interpreter to check for? And exec a separate script with that interpreter if need be to get the result.

**Comment by evanunderscore** [comment]
The global completion function has a mechanism for dynamically registering completions which is described [here](https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion.html):

> There is some support for dynamically modifying completions. This is most useful when used in combination with a default completion specified with -D. It’s possible for shell functions executed as completion handlers to indicate that completion should be retried by returning an exit status of 124. If a shell function returns 124, and changes the compspec associated with the command on which completion is being attempted (supplied as the first argument when the function is executed), programmable completion restarts from the beginning, with an attempt to find a new compspec for that command. This allows a set of completions to be built dynamically as completion is attempted, rather than being loaded all at once.
>
> For instance, assuming that there is a library of compspecs, each kept in a file corresponding to the name of the command, the following default completion function would load completions dynamically:

```
_completion_loader()
{
    . "/etc/bash_completion.d/$1.sh" >/dev/null 2>&1 && return 124
}
complete -D -F _completion_loader -o bashdefault -o default
```

Properly determining what to complete can be costly, and may require us to start multiple Python interpreters. However if the last thing we do is register a simpler completion function and return 124 to restart completion, we'll only pay that cost once per program, and subsequent completions will be faster than they are currently.

**Comment by evanunderscore** [comment]
Example of caching behavior: c101462fa2f149095e729eea950351704d723b65

Not sure if we'd want to apply this to all scripts or just the ones with entry points. The test demonstrates how a file that no longer contains `PYTHON_ARGCOMPLETE_OK` will still be completed if we do this.

**Comment by evanunderscore** [comment]
I think 84a29fc42fad2b18c1903ae9f9cbfa5b67ec259c is enough to use the correct interpreter without running Python a third time. Testing this will probably be difficult.
