### ISSUE TITLE
Wrong completions if argparse.py in module

### ISSUE THREAD

**Issue by rck** [kislyuk/argcomplete#102]
Hi,

## Versions:
-  argcomplete from yesterday (pip)
- argparse 1.3.0 from https://pypi.python.org/pypi/argparse

For my project I have to support old versions of python, therefore I ship a local argparse.py.

### Preparation
```
$ mkdir mytest
# for the version that works:
$ cp /somewhere/argparse-1.3.0/argparse.py .
# for the version that does not work:
$ cp /somewhere/argparse-1.3.0/argparse.py ./mytest
```

### subt.py
Uncomment the "works" version or any of the "does not work" versions.
```
#!/usr/bin/env python2

#works:
# import argparse as margparse
#does not work
# import mytest.argparse as margparse
# from mytest import argparse as margparse
import argcomplete
import sys

p = margparse.ArgumentParser()
s = p.add_subparsers()

l = s.add_parser('list', aliases=['l'])
se = s.add_parser('set', aliases=['s'])

l.add_argument('--foo-list')
se.add_argument('--foo-set')

argcomplete.autocomplete(p)

print p.parse_args(sys.argv[1:])
```

## OK
If subt.py and argparse.py are in the same directory, everything is fine:
```
$ ./subt.py set -<tab><tab>
--foo-set  -h         --help
$ ./subt.py list -<tab><tab>
--foo-list  -h          --help
```
## Strange behavior
If I try to import argparse from a module/subdirectory, in my case "mytest", the completion returns wrong results:
```
$ ./subt.py list <tab><tab>
-h      --help  l       list    s       set
$ ./subt.py list -<tab><tab>
-h      --help
```

**Comment by lisongmin** [comment]
try
touch mytest/__init__.py

**Comment by kislyuk** [comment]
Right, this won't work because things like `isinstance` type checks will fail, because argcomplete will be comparing e.g. `argparse.SubparserAction` to `mytest.argparse.SubparserAction` and not getting the right result. If you're going to ship a custom argparse, you have to ship a custom argcomplete that imports and uses it.

**Comment by rck** [comment]
@kislyuk Thanks, good hint! Now it works as expected.
