### ISSUE TITLE
Readline and subparsers

### ISSUE THREAD

**Issue by rck** [kislyuk/argcomplete#103]
Here the goal is to have a program that allows completion on the command line as well as in an "interactive" mode.
## Versions
- argparse: Default pyton2.7 version (1.2.1)
- argcomplete: Tried with latest pip (0.8.4) and the current git HEAD

## Code
```
#!/usr/bin/env python2

import argparse
import argcomplete
import readline
import sys

def cmd_print(args, p):
    print args

def cmd_interactive(args, p):
    completer = argcomplete.CompletionFinder(p)
    readline.set_completer(completer.complete)
    readline.parse_and_bind("tab: complete")
    while True:
        result = raw_input("> ")
        print result

p = argparse.ArgumentParser()
s = p.add_subparsers()

l = s.add_parser('list')
l.set_defaults(func=cmd_print)
se = s.add_parser('set')
se.set_defaults(func=cmd_print)
i = s.add_parser('interactive')
i.set_defaults(func=cmd_interactive)

l.add_argument('--foo-list')
se.add_argument('--foo-set')

argcomplete.autocomplete(p)

args = p.parse_args(sys.argv[1:])
args.func(args, p)
```

## Problem
The completion on the terminal's command line works as expected, but in "interactive" mode subparser arguments do not work as expected.
```
$ ./test.py interactive
> se<tab>
```
Completes to "set", great, but
```
$ ./test.py interactive
> set -<tab>
--help       -h           interactive  list         set
> set -
```

**Comment by kislyuk** [comment]
Please try with the latest master. The readline REPL completer support has been buggy, I just cleaned it up and it should be working now.

**Comment by kislyuk** [comment]
Note: follow the instructions in the docstring for `rl_complete` (https://github.com/kislyuk/argcomplete/blob/master/argcomplete/__init__.py#L508-L526). They have changed.

**Comment by rck** [comment]
@kislyuk Thanks, works as expected
