### ISSUE TITLE
Argcomplete doesn't work when script name is relative to ~

### ISSUE THREAD

**Issue by VorpalBlade** [kislyuk/argcomplete#104]
Argcomplete doesn't complete if you use a path relative to ~. This applies both to the global completion support and when activated for a single script only.

Example:
```
$ ./test-complete.py <TAB>
-h      --help  -t      --test
$ ~/test-complete.py <TAB>
Display all 110 possibilities? (y or n)
<Normal built in bash file completion result here, and no flags from the script>
$ /home/user_name/test-complete.py <TAB>
-h      --help  -t      --test
```
I used argcomplete 0.8.5 with Python 3.4 for the above example, in case that is relevant. I have *not* tested if the bug also happens with Python 2.x.

The python script in the example is a trivial test script (that I wrote to verify it wasn't my much more complicated program causing the issue), though I can attach it if you want to.

As a side note, this also appears to happen when relative an environment variable (i.e. `$HOME/test-complete.py <TAB>`), though that is not something I normally use (unlike ~-relative paths)

**Comment by kislyuk** [comment]
Thank you for the report, @VorpalBlade. I added a fix and released it in v0.8.6. Please test and let me know if it works for you.

**Comment by VorpalBlade** [comment]
Yes, this solves the issue with ~. (Though paths relative to an environment variable still don't work, but that is not something I normally use).

**Comment by kislyuk** [comment]
I think the only way to do things like variable expansion is by running eval on all of `$1`, which risks destructive side effects.
