### ISSUE TITLE
Sourcing problem

### ISSUE THREAD

**Issue by radaniba** [kislyuk/argcomplete#109]
Hello

I followed all the install steps but when adding the path to autocomplete to my .bashrc file I have this error message after sourcing

```
-bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]
```

Any idea to fix this ?

Thanks

**Comment by kislyuk** [comment]
You are running an old version of bash. Ensure that your bash is recent enough. Follow the instructions in the readme, under "Bash version compatibility" (https://argcomplete.readthedocs.org/en/latest/#global-completion).
