### ISSUE TITLE
Does this work with setuptool's entry_points ?

### ISSUE THREAD

**Issue by thorsummoner** [kislyuk/argcomplete#112]
I've setup:
`mypackage` with a setup.py like so:

```
from setuptools import setup, find_packages
setup(
    name = "HelloWorld",
    version = "0.1",
    packages = find_packages(),
    entry_points={
        'console_scripts': [
            'my-util = mymodule.util:main',
        ]
    }
)
```

I've installed in on a python 2.7 virtualenv and made `/dev/mypackage/.env` my environemnt
`python -m virtualenv .env`
`source .env/bin/activate`
Install mypackage in develop mode:
`python -m pip develop mypackage`

now the `my-util` command has been added to the virtualenv path:
`/dev/mypackage/.env/bin/my-util`

```
#!/dev/mypackage/.env/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'mypackage==0.1','console_scripts','my-util'
__requires__ = 'mypackage==0.1'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('mypackage==0.1', 'console_scripts', 'my-util')()
    )
```

`/dev/mypackage/util/__init__.py`

```
#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK
"""
My docstring
"""

import argparse
import os

ARGP = argparse.ArgumentParser(
    description=__doc__,
    formatter_class=argparse.RawTextHelpFormatter,
)
class Completer(object):
    @staticmethod
    def config(prefix, **kwargs):
        return (v for v in os.environ if v.startswith(prefix))
    @staticmethod
    def profile(prefix, **kwargs):
        return (v for v in os.environ if v.startswith(prefix))
ARGP.add_argument('--config', help='`.conf` File to Read.', default='~/mypackage.conf')\
.completer = Completer.config
ARGP.add_argument('profile', nargs='?', help='Profile Name')\
.completer = Completer.profile
argcomplete.autocomplete(ARGP)

from pprint import pprint

def main(argp=None):
    if argp is None:
        argp=ARGP.parse_args()

    print(__doc__)
    pprint(argp, width=120) 
```

---

Am I doing anything obviously wrong? I refresh my bash shell session, reactivate the virtualenv and can tab complete the my-util on the path like normal, but it doesn't autocomplete anything special from there.

**Comment by kislyuk** [comment]
Yes, it should work. Do you have argcomplete installed inside the virtualenv? If it's installed outside the virtualenv, it won't work.

**Comment by evanunderscore** [comment]
Potentially just a copy/paste error, but you don't actually `import argcomplete` anywhere. I would also generally recommend calling `argcomplete.autocomplete` inside `main` rather than at the module level.
