### ISSUE TITLE
packaging argcomplete (py2 and py3 in the same time)

### ISSUE THREAD

**Issue by ignatenkobrain** [kislyuk/argcomplete#117]
Hi,

I'm maintainer of argcomplete in Fedora. How I should package argcomplete to work both with python2 and python3? I mean which bash_completion script to use and etc.?

**Comment by kislyuk** [comment]
There is nothing special that I'm aware of that you need to do. The shell hook script is not Python but Bash, and its content does not change depending on the Python version.

If you discover any incompatibilities, please file them here.
