### ISSUE TITLE
Add = if action='store'

### ISSUE THREAD

**Issue by ignatenkobrain** [kislyuk/argcomplete#122]
```
$ ./test.py --store 
--bar    --foo    -h       --help   --store  test.py  --true 
```

``` python
parser.add_argument("--store", action="store")
```

it should not suggest other options, by default it should suggest filenames if no completer specified. If `nargs='*'` or `nargs='+'` it should take care about count of arguments.

**Comment by evanunderscore** [comment]
I think this was an issue with the default completer which was inadvertently fixed by 00210f9a7b63f940102e1305e889dc6c82613896

**Comment by evanunderscore** [comment]
@ignatenkobrain Does this work as expected for you now? I'm pretty sure nargs handling was fixed in #131.

**Comment by ignatenkobrain** [comment]
nice to see that project is not dead. I will try it asap

**Comment by evanunderscore** [comment]
Verified with a test case, feel free to open a new issue if you encounter any more problems.
