### ISSUE TITLE
argcomplete + configargparse: adding certain types of config directives to config files breaks tab-completion

### ISSUE THREAD

**Issue by ryran** [kislyuk/argcomplete#123]
I **LOVE** argcomplete. I also love [configargparse](https://github.com/bw2/ConfigArgParse), a drop-in replacement for the standard argparse which allows you to integrate config files & environment variables with standard cmdline opts.

Thankfully they work together almost flawlessly.
Almost because when I put certain types of options in a config file argcomplete totally fails. It doesn't complete ANYTHING.

**Here's a reproducer:**

```
$ cat koalaberz.py 
#!/usr/bin/python
# -*- coding: utf-8 -*-
# PYTHON_ARGCOMPLETE_OK
try:
    import configargparse
except:
    print("Missing configargparse; Run:\n  pip install configargparse\n")
    raise
try:
    import argcomplete
except:
    print("Missing argcomplete; Run:\n  pip install argcomplete; activate-global-python-argcomplete\n")
    raise

p = configargparse.ArgParser(default_config_files=['koala1.cfg','koala2.cfg'])
p.add('--togglefoo', action='store_true', help='Turn on the foo')
p.add('--appendbar', action='append', metavar='THINGS', help='Add things to bar')
p.add('--pickbaz', choices=['a', 'b', 'c'], help='Choose your baz')
argcomplete.autocomplete(p)
opts = p.parse_args()
print(opts)

$ chmod +x koalaberz.py 

$ ./koalaberz.py -h
usage: koalaberz.py [-h] [--togglefoo] [--appendbar THINGS]
                    [--pickbaz {a,b,c}]

Args that start with '--' (eg. --togglefoo) can also be set in a config file
(koala1.cfg or koala2.cfg or ) by using .ini or .yaml-style syntax (eg.
togglefoo=value). If an arg is specified in more than one place, then command-
line values override config file values which override defaults.

optional arguments:
  -h, --help          show this help message and exit
  --togglefoo         Turn on the foo
  --appendbar THINGS  Add things to bar
  --pickbaz {a,b,c}   Choose your baz
```

**Look good? Now a quick demo that the tab-completion works.**

```
$ ./koalaberz.py -                                                           <--- Pressed Tab here
--appendbar  -h           --help       --pickbaz    --togglefoo  
$ ./koalaberz.py --pickbaz                                                   <--- Pressed Tab here
a  b  c  
$ ./koalaberz.py --pickbaz a --togglefoo -                                   <--- Pressed Tab here
--appendbar  -h           --help       --pickbaz    --togglefoo  
$ ./koalaberz.py --pickbaz a --togglefoo --appendbar junk --appendbar more   <--- Pressed Enter here
Namespace(appendbar=['junk', 'more'], pickbaz='a', togglefoo=True)
```

**When I add config directives of type `store`, all is well.**

```
$ echo pickbaz = b >koala1.cfg

$ ./koalaberz.py -                                                    <--- Pressed Tab here
--appendbar  -h           --help       --pickbaz    --togglefoo  

$ ./koalaberz.py                                                      <--- Pressed Enter here
Namespace(appendbar=None, pickbaz='b', togglefoo=False)
```

**But watch what happens when I add a boolean:**

```
$ echo togglefoo = true >koala2.cfg

$ ./koalaberz.py                                                      <--- Pressed Tab here
.bash_history  .bashrc        .config/       koalaberz.py   .ssh/   
.bash_logout   bin/           koala1.cfg     .lesshst       .viminfo
.bash_profile  .cache/        koala2.cfg     repro          .vimrc  

$ ./koalaberz.py                                                      <--- Pressed Enter here
Namespace(appendbar=None, pickbaz='b', togglefoo=True)
```

**So adding a boolean toggle to a config file breaks argcomplete for some reason. ??? Note that configargparse lets you specify booleans in multiple ways, but none of them work with argcomplete.**

```
$ echo togglefoo >koala2.cfg
$ ./koalaberz.py 
Namespace(appendbar=None, pickbaz='b', togglefoo=True)

$ echo --togglefoo >koala2.cfg
$ ./koalaberz.py 
Namespace(appendbar=None, pickbaz='b', togglefoo=True)

$ echo togglefoo: true  >koala2.cfg
$ ./koalaberz.py 
Namespace(appendbar=None, pickbaz='b', togglefoo=True)
```

**Another oddity is that options of type `append` work as long as I don't actually store more than one value in the list.**

```
$ echo appendbar = barbar >koala2.cfg
$ ./koalaberz.py
Namespace(appendbar=['barbar'], pickbaz='b', togglefoo=False)
$ ./koalaberz.py -
--appendbar  -h           --help       --pickbaz    --togglefoo  

$ echo appendbar = [bar 1, bar 2] >koala2.cfg
$ ./koalaberz.py
Namespace(appendbar=['bar 1', 'bar 2'], pickbaz='b', togglefoo=False)
$ ./koalaberz.py                                                      <--- Pressed Tab here
.bash_history  .bashrc        .config/       koalaberz.py   .ssh/   
.bash_logout   bin/           koala1.cfg     .lesshst       .viminfo
.bash_profile  .cache/        koala2.cfg     repro          .vimrc  
```

Given how awesome both of these modules work together ... and how I hope they'll be in the standard library someday, I'd love to see this fixed, but of course it's an odd problem ... what do you think? Knowing the argcomplete code like you do ... do you have any ideas of what's causing this?

Thanks for reading,
Ryan

**Comment by kislyuk** [comment]
Sorry about the lengthy delay in my response to this. I unfortunately don't know enough about configargparse to figure out why this happens. Ultimately I'm surprised argcomplete works with configargparse to any extent at all. Beacuse argparse is not actually built to allow customization of the argument parsing process, argcomplete relies on runtime monkey-patching of the parser (conditional upon detecting that argument completion has been invoked). Of course this monkey-patching has no API contract to stand on, so it's brittle and will break if you replace the argparse parser with something else.

I'll try to read more into what configparse does to see if argcomplete can be more defensive. If you want to give it a try, see the "Debugging" section in the readme.

**Comment by kislyuk** [comment]
Bumping this up in my queue, since I've seen configargparse used out there a few times now. Any help welcome.

**Comment by evanunderscore** [comment]
Both issues are resolved by https://github.com/bw2/ConfigArgParse/pull/78. We don't need to make any code changes, but it might be a good idea to add a test that verifies the examples continue to work as expected.

**Comment by evanunderscore** [comment]
The boolean issue appears to have resolved itself somehow, but having multiple options of type `append` is still broken.

**Comment by evanunderscore** [comment]
@ryran I've followed through your examples with ConfigArgParse 0.12.0 and they work as expected. Thanks for the detailed report.
