### ISSUE TITLE
Autocomplete does not work on OS X

### ISSUE THREAD

**Issue by jsabin** [kislyuk/argcomplete#128]
Argcomplete works great for me on Ubuntu but I can't get it to work on the Mac. Here are my specs:

OS: 10.11.4
Python: 2.7.10
Bash: 4.3.42(1)-release
Home-brew: 0.9.9

When I run activate-global-python-argcomplete, I get the following:
usage: activate-global-python-argcomplete [-h] [--dest DEST] [--user]
                                          [--no-defaults]
                                          [--complete-arguments ...]
activate-global-python-argcomplete: error: Path /etc/bash_completion.d does not exist

I have run this command with the --dest switch and pointed to /usr/local/etc/bash_completion.d where homebrew's autocomplete file exists. I tried it in /etc/bash_completion.d after creating that directory and I tried it in ~/.bash_completion.d also with no luck. 

To test it I have been using your describe_github_user.py script. When I press TAB I get a list of files in the local directory rather than members.

./describe_github_user.py --organization heroku --member <TAB>

Can you please give me some guidance.

Thanks

**Comment by kislyuk** [comment]
Can you confirm that the output of `echo $BASH_VERSION` is 4.3.42?

Do you have requests installed? (It's necessary to run the demo script.)

**Comment by jsabin** [comment]
I did not run source /usr/local/etc/bash_completion/python-argcomplete.sh. Running this fixes the problem, but not when starting a new shell. I'm assuming this needs to be added to my .bashrc? I didn't have to do this for Ubuntu (or its being done elsewhere). Is this unique to OS X?

Thanks for your help and quick response.

**Comment by kislyuk** [comment]
`source /usr/local/etc/bash_completion` must be in your .bashrc. The reason you don't have to do it in Ubuntu is it's in the default .bashrc installed by Ubuntu for your user.
