### ISSUE TITLE
Argcomplete always sorts completions

### ISSUE THREAD

**Issue by julienbaley** [kislyuk/argcomplete#129]
Even when one writes a custom completer, argcomplete will sort that list alphabetically before printing it.

Is this something that can be changed? Or is it not linked to argcomplete?

**Comment by kislyuk** [comment]
Sorting is done by bash. I think there is nothing you can do to change it. See http://unix.stackexchange.com/questions/215937/disable-sorting-of-compreply-in-bash-complete-function

**Comment by haifengkao** [comment]
zsh can do the custom sorting
http://stackoverflow.com/questions/15140396/zsh-completion-order

**Comment by kislyuk** [comment]
Cool @haifengkao, if you have specific examples or a zsh-specific harness you want to add, let me know.
