### ISSUE TITLE
Lazy choices completer

### ISSUE THREAD

**Issue by sils1297** [kislyuk/argcomplete#137]
Hi,

we'll be needing a ChoicesCompleter that loads the choices lazy by calling a function. Mind a PR?

**Comment by sils1297** [comment]
I do have

```python
class ChoicesCompleter(object):
    """
    This class is copied and adapted from
    https://github.com/kislyuk/argcomplete.
    """
    def __init__(self, choices):
        self._choices = None

        if callable(choices):
            self._load_choices = (lambda self:
                                  setattr(self, 'choices', choices()))
        else:
            self.choices = choices

    def __call__(self, prefix, **kwargs):
        return (c for c in self.choices if c.startswith(prefix))

    @property
    def choices(self):
        if self._choices is None:
            self._load_choices(self)

        return self._choices

    @choices.setter
    def choices(self, iterable):
        """
        Initialize the choices with items from the given iterable.

        This also normalizes them to neat strings.
        """
        self._choices = []
        for choice in iterable:
            if isinstance(choice, bytes):
                choice = choice.decode(sys_encoding)
            if not isinstance(choice, str):
                choice = str(choice)
            self._choices.append(choice)
```

now. It is admittably a bit more complicated than the original one but it can deal with all variants.

**Comment by kislyuk** [comment]
I'm not quite sure if I understand your request. The point of the completer architecture is to enable lazy completion. The `choices` attribute is not special - it's not part of the protocol. Just define your completer class and put any lazy loading logic in the `__call__()` method, or pass any callable as the completer - you can define a function or even a lambda.

**Comment by sils1297** [comment]
With `lazy` I mean not executed on module import/when actually running the program but only when the completions are needed.

I'd rather contribute upstream than override just for us because it might help others as well. With that class/PR argcomplete can do that easily.

For us generating the completions takes about .5 seconds - and it's also performed when we e.g. call the help or the version of our binary.

**Comment by sils1297** [comment]
I.e. yes, we can do this downstream as well but I see no reason you and other users shouldn't get that code as well.

**Comment by kislyuk** [comment]
The completer architecture is inherently lazy. It seems to me your additions overcomplicate the completer. If `choices` is a callable, I believe I can accomplish what you wrote with simply:
```
parser.add_action("--foo").completer = choices
```
(Although this doesn't filter by prefix, both arcomplete and bash actually double check that.)

**Comment by sils1297** [comment]
The architecture is, the ChoicesCompleter class is not. I see how writing a simple function would be simpler this way - are you implying that I actually don't have to filter the choices by prefix and I can indeed just give it my callable which returns a list with lru_cache?

**Comment by kislyuk** [comment]
Right, you should be able to. Let me know if you run into any issues. Your callable does have to accept the 4 keyword args that get passed to completers. If your callable's signature is inflexible, you can just add a basic wrapper like:
```
parser.add_action("--foo").completer = lambda *args, **kwargs: choices()
```

**Comment by sils1297** [comment]
Neat, that works like a charm. Why do you have the prefix complexity in the completers if it's not needed? That could simplify some things.

**Comment by kislyuk** [comment]
Because in some completers it might reduce the amount of work done retrieving the completions. You're right though, I should clarify in the docs that this step is not required.
