### ISSUE TITLE
Anyone got this working with bash from git for windows?

### ISSUE THREAD

**Issue by krist10an** [kislyuk/argcomplete#142]
After some debugging, it seems it has issues opening fd 8 on my computer :
"Unable to open fd 8 for writing, quitting"

$ git --version
git version 2.10.0.windows.1

$ bash --version
GNU bash, version 4.3.46(2)-release (x86_64-pc-msys)

**Comment by kislyuk** [comment]
Can you run the following on your Windows system and let us know the full output?
```
python -c 'import os; os.fdopen(8)'
python -c 'import os; os.fdopen(8, "w")'
python -c 'import os; os.fdopen(8, "wb")'
```

**Comment by krist10an** [comment]
Sure:

```
$ python -c 'import os; os.fdopen(8)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 9] Bad file descriptor

$ python -c 'import os; os.fdopen(8,"w")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 9] Bad file descriptor

$ python -c 'import os; os.fdopen(8,"wb")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 9] Bad file descriptor

```

**Comment by krist10an** [comment]
For reference I get the same result from Linux (Ubuntu 16.04,1 LTS x64, Python 2.7,.12):

```
vagrant@vagrant:~$ python -c 'import os; os.fdopen(8)'
python -c 'import os; os.fdopen(8, "wb")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 9] Bad file descriptor
vagrant@vagrant:~$ python -c 'import os; os.fdopen(8, "w")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 9] Bad file descriptor
vagrant@vagrant:~$ python -c 'import os; os.fdopen(8, "wb")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 9] Bad file descriptor
```

**Comment by evanunderscore** [comment]
You can only open that fd if you create it:

```
python -c 'import os; os.fdopen(8)' 8>&1
python -c 'import os; os.fdopen(8, "w")' 8>&1
python -c 'import os; os.fdopen(8, "wb")' 8>&1
```

Unfortunately this doesn't seem to work for me on Windows (in bash or cmd).

**Comment by krist10an** [comment]
Aha.. that makes sense :-)
With those commands I get it working in Linux while it does not work in Windows.

**Comment by evanunderscore** [comment]
I can't find any way to open these extra fd's on Windows, but I did get this working by writing to and reading from a temporary file instead: https://github.com/evanunderscore/argcomplete/commit/f88af05b6fe77646e380222a4b9c0c289de75b14

Perhaps this solution would be acceptable if it was modified to only do this on Windows?

**Comment by kislyuk** [comment]
I'm a bit worried about that solution. First, both bash and python would have to detect a particular version of windows reliably. Second, if you can't rely on fds, I wonder how many assumptions you can make about mktemp working or tempdir permissions working or being able to clean up the file afterward.

**Comment by evanunderscore** [comment]
Only Python would have to know where it's running and generate a script accordingly. I'm not sure what you mean about tempdir permissions, but I think getting the script to call `mktemp`, pass the filename in an environment variable, then delete it after reading it should work fine.

**Comment by kislyuk** [comment]
I mean that we may not have permissions to write to tempdir, and need to gracefully handle that case.

Instead of using files, I'd prefer to first try to figure out why fds don't work on msys, and what the preferred IPC alternative is. Using files for IPC, no matter how limited in scope, introduces a big design liability.

**Comment by evanunderscore** [comment]
At least for me, `/tmp` maps to `C:\users\<user>\appdata\local\temp`, which should never have permission problems.

[This page](https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/redirection.mspx?mfr=true) confirms that these fds should exist, I just can't interact with them using `os.fdopen` (whether I'm using cmd.exe or bash). I do agree that using a temporary file is not great.

**Comment by krist10an** [comment]
@evanunderscore I tested your patch, and it works on my computer 👍 
My /tmp is also mapped to %appdata%/local/temp on Windows 7/10

**Comment by kislyuk** [comment]
I think it's unwise to try to accommodate behaviors of platforms that don't support fds, so I don't think we should go with the tempfile solution.

If anyone can figure out how to create and handle fds under msys, we could proceed by conditionally enabling whatever workaround is necessary for that. I have a hard time believing msys doesn't support fd handling at all, since fds are fundamental to so many things in the programs involved.

**Comment by evanunderscore** [comment]
I think this is the source of the problem:

https://www.python.org/dev/peps/pep-0446/#inheritance-of-file-descriptors-on-windows

> Using CreateProcess() , handles are only inherited if their inheritable flag ( HANDLE_FLAG_INHERIT ) is set and the bInheritHandles parameter of CreateProcess() is TRUE ; all file descriptors except standard streams (0, 1, 2) are closed in the child process, even if bInheritHandles is TRUE .

I'm guessing the shell uses CreateProcess(), which means none of the fds would ever make it to Python.

There's some similar discussion at http://grokbase.com/t/python/python-dev/137q5t2d39/inherance-of-file-descriptor-and-handles-on-windows-pep-446. The example given doesn't involve a command line but the end result looks the same.

**Comment by kislyuk** [comment]
I'm going to go ahead and close this. My recommendation to those affected is to either use the Ubuntu Linux subsystem for Windows 10, or research a workaround that doesn't involve the use of tempfiles.
