### ISSUE TITLE
Exclusive groups are repeated on the compilation

### ISSUE THREAD

**Issue by zacharya19** [kislyuk/argcomplete#144]
When adding exclusive groups, the autocompletion will continue to offer all the members of the group although only one of them can be chosen.
Example:
```
#!/usr/bin/env python
import argparse
import argcomplete

parser = argparse.ArgumentParser()

group = parser.add_mutually_exclusive_group()
group.add_argument('--test', action='store_true')
group.add_argument('--no_test', action='store_true')
argcomplete.autocomplete(parser, exclude=['-h', '--help'])
args = parser.parse_args()
```
Expected:
```
$ ./test.py <tab>
--test --no_test
$ ./test.py --test <tab>
```

I could not found a solution here, when I used my code (PR #143), I got close, but because it's exclusive, if I chose --test no I will get forever --no_test on the compilation because it's always False.

**Comment by kislyuk** [comment]
Thanks, I haven't worked with exclusive groups before and I definitely agree they should be filtered.

**Comment by evanunderscore** [comment]
@zacharya19 I noticed you said you fixed this on your branch but I couldn't get it to work. I'm not sure if I'm using it correctly - could you add a test case?

I also took a look at this (just the mutual exclusion problem, not duplicate flags) and came up with 9c46dd5ecfe0335cd501c6dfebe91c0be00e747f. If you or @kislyuk like this solution I can make a PR.

**Comment by zacharya19** [comment]
Here is how I use it for example:

```python
parser = argparse.ArgumentParser()

sub = parser.add_subparsers()
cmd = sub.add_parser('hi')
cmd.add_argument('--tag', choices=['e', 'm', 'f'])

group = cmd.add_mutually_exclusive_group()
group.add_argument('--test', action='store_true')
group.add_argument('--no_test', action='store_true')

argcomplete.ExclusiveCompletionFinder().__call__(parser, exclude=['-h', '--help'])
```

**Comment by kislyuk** [comment]
@evanunderscore, thank you, that's beautiful. I took a quick look at this myself yesterday and realized the logic is somewhat complex. But I missed the opportunity to leverage an argparse builtin method for this purpose, which makes it much better. Please send a PR.
