### ISSUE TITLE
Make COMP_TYPE available to completion functions

### ISSUE THREAD

**Issue by mattclay** [kislyuk/argcomplete#156]
It would be useful for the `COMP_TYPE` environment variable to be available in a custom completion function, either from `os.environ` or as a keyword argument passed to the function.

This would allow a completion function to respond differently depending on the type of completion, such as differentiating between single tab and double tab completion.

A minimal implementation would only require adding `COMP_TYPE="$COMP_TYPE" \` in two places:

- [argcomplete/bash_completion.d/python-argcomplete.sh#L42](https://github.com/kislyuk/argcomplete/blob/db2c2fa1835b4fb80e90240ea01f04c05426762b/argcomplete/bash_completion.d/python-argcomplete.sh#L42)
- [scripts/register-python-argcomplete#L29](https://github.com/kislyuk/argcomplete/blob/4e278d80735c89346a8b91b4c7a5192b13ef5377/scripts/register-python-argcomplete#L29)

**Comment by kislyuk** [comment]
Sounds good to me, can you open a PR?

**Comment by mattclay** [comment]
@kislyuk Do you have a preference for just exposing the environment variable vs making it available as a keyword argument to the completion function?

**Comment by kislyuk** [comment]
I would prefer to just expose the variable. Offering it as a keyword argument changes the signature, which even with kwargs carries a compatibility risk for downstream completer implementers who didn't bother to insert a **kwargs wildcard at the end. I think this feature by itself doesn't merit changing the signature.
