### ISSUE TITLE
argcomplete does not parse commas the same way argparse does

### ISSUE THREAD

**Issue by bbejot** [kislyuk/argcomplete#161]
It appears that argcomplete, after seeing a comma, thinks that it is on the next parameter.  This is different than argparse, which parses a comma-separated list as a single parameter.

for example, with the following code snippet:
```
def completer_ab(**k):
    return ['a,b']

def completer_c(**k):
    return ['c']

...
    # adding arguments to the parser
    action.add_argument(dest='var_1').completer = completer_ab
    action.add_argument(dest='var_2').completer = completer_c
...

```
then calling
`<progname> a,<TAB><TAB>`
will suggest "c" instead of "a,b".

However, calling
`<progname> a,b c`
will parse "a,b" as the value of "args.var_1" and "c" as the value of "args.var_2"

**Comment by kislyuk** [comment]
@evanunderscore, any ideas on this one? I can reproduce it on master.

**Comment by evanunderscore** [comment]
You can probably fix the immediate issue by adding comma to https://github.com/kislyuk/argcomplete/blob/75bc04b7d457bb865453b2bcd767b68b5df936a8/argcomplete/my_shlex.py#L83. But perhaps `wordchars` should really be any characters that aren't otherwise special?

**Comment by evanunderscore** [comment]
After looking a little more closely, it seems that we should really just be setting `whitespace_split` to `True` in the same way that `split` does. I noticed this line came from the patch in http://bugs.python.org/issue1521950 - I'll voice my concerns on the Python bug tracker.

**Comment by evanunderscore** [comment]
I've created http://bugs.python.org/issue28595 to address this issue. Note that the changes I've proposed in that ticket, when applied to `my_shlex`, should also remove the need for the handling with `UnicodeWordchars`.

**Comment by kislyuk** [comment]
@evanunderscore, it seems to me your patch in http://bugs.python.org/issue28595 is wrong. shlex.shlex should tokenize like the shell, that's the point of the prior patch. The fact that you had to change this test seems to indicate the solution is wrong:
```
-        ref = ['~/a', '&', '&', 'b-c', '--color=auto', '||', 'd', '*.py?']
-        ss = "~/a && b-c --color=auto || d *.py?"
+        ref = ['~/a&&b-c', '--color=auto', '||', 'd', '*.py?']
+        ss = "~/a&&b-c --color=auto||d *.py?"
```
Bash will split that string along `&&` but with your changes, shlex won't.

**Comment by evanunderscore** [comment]
I should have made it clearer why I was changing that line. The actual test is  being run with `s = shlex.shlex(ss, punctuation_chars="|")` on the line below, which means it should *not* treat `&` as a special character. Without changing the test case, it wouldn't actually demonstrate the effect of `punctuation_chars` after the patch - it would return both `&&` and `||` as tokens.

If the original case were left in, this would be the change:

```
-        ref = ['~/a', '&', '&', 'b-c', '--color=auto', '||', 'd', '*.py?']
+        ref = ['~/a', '&&', 'b-c', '--color=auto', '||', 'd', '*.py?']
```

**Comment by evanunderscore** [comment]
@kislyuk Do you remember your reasoning for vendoring a copy of shlex with these fixes in the first place? Switching the current implementation to use `whitespace_split` instead of `punctuation_chars` fixes this bug plus another expected failure case, without breaking any of the other tests.

**Comment by evanunderscore** [comment]
I'm going to merge the associated PR. I'm fairly certain we don't need `punctuation_chars`, but if this somehow breaks something, let me know.
