### ISSUE TITLE
register-python-argcomplete with a complete path

### ISSUE THREAD

**Issue by mnieber** [kislyuk/argcomplete#165]
I ran into a gotcha where I tried to register my script using `register-python-argcomplete /home/maarten/foo.py`. I used the full path to ensure that completion is only triggered for exactly this executable. I guess that's just not how it works, but it might be helpful to point this out in the documentation.

Thanks for writing argcomplete,
Maarten

**Comment by evanunderscore** [comment]
@mnieber @JackofSpades707 I've updated the README to clarify how this works. Please let me know if this is still unclear.
