### ISSUE TITLE
Is it possible to support auto completion in PowerShell (PoSh)?

### ISSUE THREAD

**Issue by Paebbels** [kislyuk/argcomplete#166]
Windows is shipped with PowerShell since years. The current version is 5.0 and the next release will be available on Linux and Mac OS too. It supports auto completion like Bash.

Is there any support for PowerShell planned?

(I could assist to implement it to some degree, but I can't offer a complete ready to use PR :).

**Comment by kislyuk** [comment]
I'm open to it, but I don't use powershell, so you or someone else will have to come up with a PR.

Here is a good starting point: https://github.com/lzybkr/PSReadLine/issues/194

**Comment by kislyuk** [comment]
Not interested in supporting PowerShell at this point.

**Comment by aviita** [comment]
@kislyuk, so should it work in bash? Does not work for me in Ubuntu on WSL.

**Comment by kislyuk** [comment]
@aviita yes, argcomplete works in bash. If you have problems making it work, please open a new issue and describe the full steps to reproduce.

**Comment by aviita** [comment]
@kislyuk , 

Thanks. Sorry I failed to respond my self yesterday evening. I did get it working by installing azure cli again in bash. Also had to note that it only works with double tab press. Thanks.
