### ISSUE TITLE
[Tab] Not calling argcomplete or Silently Erroring?

### ISSUE THREAD

**Issue by JackofSpades707** [kislyuk/argcomplete#171]
I am using:
> ArchLinux
> zsh 5.3
> oh-my-zsh
> python 3.5.2
> python-argcomplete 1.6.0-1 (installed from the archlinux AUR, python3 version)

first steps :
> activate-global-python-argcomplete --dest=/home/jack/.dotfiles/zsh/
> edit .zshrc
> Spawn new terminal to test

my .zshrc (relative to this repo) : 
> autoload -Uz +X compinit bashcompinit
> compinit
> bashcompinit
> source ~/.dotfiles/zsh/python-argcomplete.sh # This is where I set the dest
> eval "$(register-python-argcomplete /home/jack/repos/blah/myscript.py)"
> eval "$(register-python-argcomplete /home/jack/describe_github_user.py)"
 
Desire behavior : 
> Basic Tab completion

Suspected Actual behavior :
> Silently errors/doesn't make call on [TAB]?
https://i.imgur.com/4HcJ3db.png (With all my ZSTYLE code commented out)

Things I have tried :
> commenting out all ZSTYLE code in my ~/.zshrc
> Fixed common shebang issue with dos2unix (\r at the end of shebang throws interpreter error)
> chmod +x python-argcomplete.sh (This wasn't executable before-hand)
> chmod +x $some-python-script.py (to make sure it can execute the autocomplete function)
> importing lib (works just fine)
> Interactive python shell on myscript.py (couldn't get any useful output regarding this issue)
> reading docs & source code for answers

How I generated debug log : 
`PROGNAME=./myscript TEST_ARGS='--' _ARC_DEBUG=1 COMP_LINE="$PROGNAME $TEST_ARGS" COMP_POINT=31 _ARGCOMPLETE=1 $PROGNAME 8>&1 9>>~/autocomplete_debug.log`

Debug log : 
```
parsed args: (Namespace(add_user=False, defaults=False, edit_user=False, init_db=False, list_user=False, start_user=False, stop_user=False), [])
all active parsers: [MonkeyPatchedIntrospectiveArgumentParser(prog='myscript.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)]
active_parser: MonkeyPatchedIntrospectiveArgumentParser(prog='myscript.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)
optional options: ['--help', '--add-user', '--edit-user', '--stop-user', '--start-user', '--defaults', '--list-user', '--init-db']
next_positional: None
Active actions (L=0): []
active options: ['--help', '--add-user', '--edit-user', '--stop-user', '--start-user', '--defaults', '--list-user', '--init-db']
display completions: {'--stop-user': 'stop thread running for user', '--start-user': 'start thread for user', '--init-db': 'Create the database', '--defaults': 'default user settings', '--list-user': 'list single user settings', '--edit-user': 'change user settings in the database', '--add-user': 'add new user to the database', '--help': 'show this help message and exit'}
Returning completions: ['--help', '--add-user', '--edit-user', '--stop-user', '--start-user', '--defaults', '--list-user', '--init-db']
```

myscript.py code :
```
#!/usr/bin/python3
# PYTHON_ARGCOMPLETE_OK

from argparse import ArgumentParser
import argcomplete
parser = ArgumentParser()
parser.add_argument('--add-user', help='add new user to the database', default=False, action='store_true')
parser.add_argument('--edit-user', help='change user settings in the database', default=False, action='store_true')
parser.add_argument('--stop-user', help='stop thread running for user', default=False, action='store_true')
parser.add_argument('--start-user', help='start thread for user', default=False, action='store_true')
parser.add_argument('--defaults', help='default user settings', default=False, action='store_true')
parser.add_argument('--list-user', help='list single user settings', default=False, action='store_true')
parser.add_argument('--init-db', help='Create the database', default=False, action='store_true')
argcomplete.autocomplete(parser, validator=None)
args = parser.parse_args()
```

Additional Info : 
$ register-python-argcomplete ~/repos/blah/myscript.py
```
_python_argcomplete() {
    local IFS='
               '
    COMPREPLY=( $(IFS="$IFS"                   COMP_LINE="$COMP_LINE"                   COMP_POINT="$COMP_POINT"                   _ARGCOMPLETE_COMP_WORDBREAKS="$COMP_WORDBREAKS"                   _ARGCOMPLETE=1                   "$1" 8>&1 9>&2 1>/dev/null 2>/dev/null) )
    if [[ $? != 0 ]]; then
        unset COMPREPLY
    fi
}
complete -o nospace -o default -F _python_argcomplete "/home/jack/repos/blah/myscript.py"
```

**Comment by evanunderscore** [comment]
It looks like you have the same problem as #165. Does it work if you use `eval "$(register-python-argcomplete ./describe_github_user.py)"`?

**Comment by JackofSpades707** [comment]
Yes I have, both in my .zshrc and in the shell (and for both my script and the example github script)
No matter how I follow the directions I cannot get tab completion working :/

**Comment by JackofSpades707** [comment]
Oh wow. After your question I noticed that register-python-argcomplete takes args of it's own and decided to check that out, this is what fixed it for me.

> eval "$(register-python-argcomplete myscript.py -s bash)" 

Looks like for one reason or another I have to explicitly tell it to use bash completion. Regardless I'm thrilled to have tab completion now :)

**Comment by evanunderscore** [comment]
The default for that option should be "bash" so is it possible there was some caching going on and it only happened to start working when you added that option?

The resolution to #165 should be better documentation on how `register-python-argcomplete` actually works.
