### ISSUE TITLE
Specify test requirements in setup.py

### ISSUE THREAD

**Issue by htgoebel** [kislyuk/argcomplete#186]
Please specify the test requirements in setup.py. They are currently hidden in the .travis.yml and the Makefile. Thanks.

**Comment by kislyuk** [comment]
Hi, thanks for filing the bug, is there a specific use case where you need the test dependencies in setup.py? I have found that the way Python installs setuptools test dependencies is not useful in my test workflow, so I don't use them.

**Comment by htgoebel** [comment]
I'm maintaining Python packages for Guix and it's *much* easier if we do not need to dig into some travis.yml, tox.ini or requirements files. And setuptools has this cool `tests_require` entry,

**Comment by htgoebel** [comment]
Thanks :-)
