### ISSUE TITLE
Parser is not passed through to completer

### ISSUE THREAD

**Issue by evanunderscore** [kislyuk/argcomplete#200]
This appears to have been unintentionally removed in 5bfae2fa6b4e3291ffd9067b79340ae229c7b9a8. Should it be added back in?

**Comment by ttonelli** [comment]
Just spent a few hours on this issue too, and was about to open a ticket. I had an old version of argcomplete and updating it broke my old completers.

However, I do not really need the parser argument. If it is indeed to be removed, the README should at least be changed to reflect that.

**Comment by kislyuk** [comment]
Definitely a bug. Let's get it back in.

**Comment by kislyuk** [comment]
Also, we need a test for the entire completer interface (d'oh).
