### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by KOLANICH** [kislyuk/argcomplete#208]
As I understand it can be used to execute the code is not meant to be executed. I mean that if someone downloaded a malicious python code and hit tab thinking nothing malicious will happen. So I think the app must in clear way warn about it.

**Comment by kislyuk** [comment]
The only time when argcomplete runs the completion target is under the following circumstances:

- Global completion is enabled
- The completion target contains the string "PYTHON_ARGCOMPLETE_OK"
- The completion target's name is typed on the command line in such a way that if ENTER was pressed, the completion target would run
- TAB is pressed

To expose themselves to malicious code executing, the user would have to download it and prepare to explicitly run it on the command line.

There is a note in the readme already regarding the fact that completions are generated by running the completion target.

I'm inclined to dismiss this as not a security issue.

**Comment by KOLANICH** [comment]
TAB is usually not meant to execute a script in which command line it is pressed. This tool violates it. This means a one cannot be fure if pressing TAB safe when your tool is installed and global completeon is enabled. The tool should warn about it and ask for confirmation.

Another idea is to create a reduced mode which will just scan any python files with a regex, parse its argparse directives and make help based on them without actually executing the code. It has limitations, but it will be more safe.

**Comment by kislyuk** [comment]
Sounds good, thanks for your feedback. You're welcome to write such a tool. On my end, I don't consider this to be a security issue, so I'll close this for now.
