### ISSUE TITLE
"Bad file descriptor" under unit test

### ISSUE THREAD

**Issue by cherba** [kislyuk/argcomplete#209]
Unit tests which repeatedly exercise argcomplete in the output contain multiple occurrences of:
```
  close failed in file object destructor:
  IOError: [Errno 9] Bad file descriptor
```

which seems to be related to
```
       global debug_stream
       try:
           debug_stream = os.fdopen(9, 'w')
       except:
           debug_stream = sys.stderr
```

If the above is guarded by
   `if _DEBUG:`
where (`_DEBUG = '_ARC_DEBUG' in os.environ`) the message disappears.

**Comment by kislyuk** [comment]
Thanks for reporting, the `os.fdopen(9, 'w')` behavior is needed and should not be disabled. The error seems to occur in the `mute_stderr` function, and in particular I think could be related to a bug in https://github.com/kislyuk/argcomplete/pull/110. I'll need to look at this more carefully.

**Comment by kislyuk** [comment]
This should be fixed now. Please reopen if you see it again.
