### ISSUE TITLE
Update debian package on Ubuntu

### ISSUE THREAD

**Issue by BrunnerLivio** [kislyuk/argcomplete#210]
Hey there! 

Can you update the debian package (on Ubuntu 16.04) ?

The current version of argcomplete using `python3-argcomplete` and `python-argcomplete` is on 0.8.1-1ubuntu2, which is really outdated.

**Comment by kislyuk** [comment]
I'm not an Ubuntu package maintainer. The correct place for this bug is on the Debian or Ubuntu issue tracker.
