### ISSUE TITLE
Is the difference from bash file completion intentional?

### ISSUE THREAD

**Issue by plasticassius** [kislyuk/argcomplete#214]
When I have a directory structure like a/b/c, successive tabs in bash produce
```
ls a/
ls a/b/
ls a/b/c/
```
However, with argcomplete, I get
```
./t.py a -
```
where the a has `a` trailing space, so the next tab moves onto the next argument which it partially completes with `-`

Is this intentional? My first impression is that it should behave the same with files as bash does without argcomplete. Am I missing something? The code in t.py is
```
#!/usr/bin/python3
#PYTHON_ARGCOMPLETE_OK

import argparse
parser = argparse.ArgumentParser()
parser.add_argument('arg')

import argcomplete
argcomplete.autocomplete(parser)
```

**Comment by evanunderscore** [comment]
No, this shouldn't be happening. Which version of argcomplete are you using?

**Comment by plasticassius** [comment]
It looks like I have version 0.8.1 that installed with `apt install python3-argcomplete` on ubuntu 16.04.

**Comment by plasticassius** [comment]
Ok, so I found out about
```
apt install python-pip python3-pip
pip install argcomplete
pip3 install argcomplete
```
and problem is solved. Thanks for your help.
