### ISSUE TITLE
TestBashGlobal::test_python_not_executable fails with non-english locale

### ISSUE THREAD

**Issue by SpotlightKid** [kislyuk/argcomplete#217]
The test fails at [this line](https://github.com/kislyuk/argcomplete/blob/master/test/test.py#L1102).

For example, in a German locale the error message returned by `self.sh.run_command` is `'bash: ./prog: Keine Berechtigung\r\n'` and of course doesn't contain the string the test looks for.

Setting `LANG=en_US.UTF-8` or even `LC_ALL=C` somehow should fix this.

**Comment by kislyuk** [comment]
Thanks for reporting. Could you check if `import os; print(os.strerror(13))` returns `Keine Berechtigung`?

**Comment by SpotlightKid** [comment]
No, it doesn't:

```
$ echo LANG=$LANG
LANG=de_DE.UTF-8
$ python2
Python 2.7.13 (default, Dec 21 2016, 07:16:46) 
[GCC 6.2.1 20160830] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os; print(os.strerror(13))
Permission denied
$ python3
Python 3.6.0 (default, Jan 16 2017, 12:12:55) 
[GCC 6.3.1 20170109] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os; print(os.strerror(13))
Permission denied
```

**Comment by evanunderscore** [comment]
My intent was to ensure that the script was not able to be run as `./prog` since this is how global completion used to run things even when the user was completing `python ./prog`. The simplest fix seems to be not to check the message at all.

**Comment by kislyuk** [comment]
You should be able to check for the exit code instead. I think it should always be 126.
