### ISSUE TITLE
Skip completion for specific argument

### ISSUE THREAD

**Issue by dirk-thomas** [kislyuk/argcomplete#223]
I would like a specific argument (e.g. `--foo`) to not appear in the completion. Since the application is pretty modular I can't configure e.g. the global `CompletionFinder`. I found the option to set `help=argparse.SUPPRESS` but I still want a help text to be shown for `--help`.

I was thinking if something like this would be feasible:

```
arg = parser.add_argument('--foo', help='awesome option')
arg.completer = False
```

If anyone could be give me some pointers I am happy to provide a PR for this feature idea.

**Comment by kislyuk** [comment]
Sounds like a good idea. My preference would be to create a special completer class in https://github.com/kislyuk/argcomplete/blob/master/argcomplete/completers.py, `class SuppressCompleter` or something like that, and then its optional strings will be suppressed from completions. So you'd say:
```
arg = parser.add_argument('--foo', help='awesome option')
arg.completer = argcomplete.completers.SuppressCompleter
```
You need to add the new class, logic to https://github.com/kislyuk/argcomplete/blob/e72c5fb565300b935de3247e4cb84c4253471669/argcomplete/__init__.py#L348-L350 (same branch path as the one triggered by argparse.SUPPRESS), and a test.

**Comment by dirk-thomas** [comment]
@kislyuk Thank you for the detailed pointers. Based on that I was able to create #224. Beside on test related question on that PR it seemed pretty straight forward.
