### ISSUE TITLE
Global completion doesn't work for packages installed from wheels

### ISSUE THREAD

**Issue by pavelrad** [kislyuk/argcomplete#225]
[pytest](https://github.com/pytest-dev/pytest) has its command line scripts installed via [setuptools.setup(entry_points={'console_scripts': ...})](https://github.com/pytest-dev/pytest/blob/master/setup.py#L69) construction. If I understand correctly, argcomplete's global completion should handle this case and work just fine in such a situation, but it doesn't.
Looks like [this if statement](https://github.com/kislyuk/argcomplete/blob/master/argcomplete/bash_completion.d/python-argcomplete.sh#L49) should cover such a case, but `pytest` script created after installation doesn't have any of these strings in it. Here is the full content of `pytest` script from my environment:
```
#!/Users/pavel/.pyenv/versions/3.6.1/envs/test_env/bin/python3.6

# -*- coding: utf-8 -*-
import re
import sys

from pytest import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
`pytest` module from which `main` function is imported has `# PYTHON_ARGCOMPLETE_OK` as its first string.

I've opened a ticket in pytest project (see https://github.com/pytest-dev/pytest/issues/2725), but it looks like that this is a problem of argcomplete.

**Comment by evanunderscore** [comment]
It looks like the `EASY-INSTALL-ENTRY-SCRIPT` stopped being added to scripts like this some time ago. Unfortunately there's not really any distinguishing mark in them now. I'm not sure how we would go about detecting that we should follow the script.

**Comment by pavelrad** [comment]
Looks like I've found the cause of this problem. When a package is installed from a 'wheel', 'entry_points' are processed by 'pip' and resulting scripts doesn't contain `# EASY-INSTALL-...` string. If a package is installed with `pip install --no-use-wheel` or `python setup.py install` command, command line scripts are being created by setuptools and contain such lines, so the global completion works as expected.

**Comment by pavelrad** [comment]
As a workaround: configure pip to not use binaries for pytest installation. I've added `export PIP_NO_BINARY="pytest"` to my `.bash_profile` and now the global completion works for pytest in every environment, where pytest is installed from sources.

**Comment by evanunderscore** [comment]
Perhaps this could be raised as an issue with wheel? They don't have to replicate the `# EASY-INSTALL-...` string, but if it had some kind of marker to indicate it was a wheel-generated file we could look for that.

**Comment by nicoddemus** [comment]
I agree with @evanunderscore, we should raise an issue in [pip](https://github.com/pypa/pip) and see what they have to say. Could you do that @pavelrad?

**Comment by pavelrad** [comment]
Filed https://github.com/pypa/pip/issues/4702.

**Comment by nicoddemus** [comment]
Thanks @pavelrad!

**Comment by evanunderscore** [comment]
I've got a solution based on the suggestion from @RonnyPfannschmidt that we check for an entry point in the corresponding interpreter. See 3fecde312e8f74a4298ce114cb7ad666e7496a31 for details. I'm doing a few sanity checks so we don't try to run any Python script that happens to share a name with an actual console script.

**Comment by mbdevpl** [comment]
FYI: In upstream issue https://github.com/pypa/pip/issues/4702 the consensus is that they will not do anything about it. And the solution in PR #241 is working for me after rebasing onto current master.
