### ISSUE TITLE
Tab Completion - Cliff + argcomplete - Dynamic generation of choices for argument values

### ISSUE THREAD

**Issue by sradhakrishna** [kislyuk/argcomplete#231]
Hi,

We are using Cliff ([https://github.com/openstack/cliff](https://github.com/openstack/cliff)) as our command line interface. It uses argparse to provide commands.

I am trying to integrate argcomplete into my cliff app to provide choices for argument values at runtime. For e.g., when a user types in this command, 

scheduletravel --from <location> --to <location> ...

and hits Tab - Tab after --from (and --to), I'd like to display a list of values that are determined at runtime (by querying a service, for e.g.).

Specifying the argcomplete part in the cliff Command was easy - but when I run it - I don't the tab-completion working.

Can you please take a look and see if argcomplete will integrate easily with Cliff?

Any pointers will be greatly appreciated.

**Comment by evanunderscore** [comment]
If cliff uses argparse under the hood and you can get access to the parser then theoretically all you should have to do is call `argcomplete.autocomplete(parser)` as usual. If you can give me a simple reproducible example and a description of what you expected to work but didn't, I can take a look.

**Comment by kislyuk** [comment]
Closing due to lack of response from the reporter.
