### ISSUE TITLE
[docs] clarify required input paramiters for .completer attribute

### ISSUE THREAD

**Issue by ava-dylang** [kislyuk/argcomplete#242]
I had a hard time picking this tool up as the only mention that the completer has extra args is from an example `(prefix, parsed_args, **kwargs)`, witch doesn't even show the complete argform, nor does the source even indicate that kwargs are expected/used for any of the stock completers. So I'm confused and i've just assumed that all my completers need to accept `(**_)`

**Comment by evanunderscore** [comment]
The arguments are listed in the documentation: https://github.com/kislyuk/argcomplete#specifying-completers

All four of these will be passed, so you must accept them, however I've found in the vast majority of cases you'll want to ignore them and return an unfiltered list (which will be filtered on prefix for you), hence the `**_`.

How would you like to see the documentation clarified?

**Comment by ava-dylang** [comment]
Oh my bad, I guess in the defacto-example it would have been nice to see them all referenced. That is clerical enough for me. Thank you kindly for pointing it out. :bowing_man:

**Comment by evanunderscore** [comment]
I went on a little bit of a crusade a while back trying to *remove* more things from the examples in response to #139. If you (or anyone else) can come up with good uses for the other parameters I'd like to include them somewhere as examples.
