### ISSUE TITLE
[docs] clarify recomendation for `PYTHON_ARGCOMPLETE_OK` declaration

### ISSUE THREAD

**Issue by ava-dylang** [kislyuk/argcomplete#243]
I was initially under the impression that argcompleter would load my python module and check if its namespace _contained_ a 'PYTHON_ARGCOMPLETE_OK' attribute, as in the docs it is only mentioned that this key is needed, so for now i'm running with scissors declaring `PYTHON_ARGCOMPLETE_OK = True` in my module's constants block. However its possible that this form could be pushed down the file outside of that 1024-byte head that is mentioned is scanned. I would ask that the docs give a clear example of how this is expected to be used. I considered this as an option:

```
#!/usr/bin/env python3
# pragma: PYTHON_ARGCOMPLETE_OK

""" Header Doc
"""
...
```
(oh I also found that touching this text at all seemed to break argcomplete until I opened a new shell, so I haven't actually tested that this form works, I am a bit gunshy of touching it as every time I do it stops working) 

though I'm not sure it would operate well with shell-style header docs, this may assumedly needs to come after a copyright notice, witch often use the shell-style header docs (though often this is only used as a comment on the source itself, not on the module docstring, so having it appear in that shell-style header might be totally fine). I dunno, I suppose I would think it really neat if argcomplete could check the namespace of function invoked by setuptool's console_script for a specific attribute; then there aren't conflicts with needing to be within a specific byte range of the file - but I also haven't thought of an implementation that could achieve that generically.

So i dunno, would be nice to have more examples of the different supported argcomplete schemes. Maybe even embed some example projects simmilar to what the pypa/sampleproject does.

Thank you

**Comment by evanunderscore** [comment]
Thanks for reporting - I'm always looking for ways to improve the documentation so I'm happy to take any suggestions you have.

I'm not sure how you ended up with the impression that you needed a variable; all of the examples in the README, plus the example in `docs/examples` look like this:

```
#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK
...
```

The section on Global Completion states that "bash will look for the string PYTHON_ARGCOMPLETE_OK in the first 1024 bytes of any executable that it's running completion for", which is exactly what it does.

We could conceivably look for a variable called PYTHON_ARGCOMPLETE_OK without actually importing the module using `ast.parse` or similar, but what would that give us over the current implementation?

> (oh I also found that touching this text at all seemed to break argcomplete until I opened a new shell, so I haven't actually tested that this form works, I am a bit gunshy of touching it as every time I do it stops working)

During development, if you try to complete something that fails, you'll probably end up with a default completer registered. You'll have to restart your shell or delete that (see https://github.com/kislyuk/argcomplete#common-problems).

**Comment by ava-dylang** [comment]
> in the first 1024 bytes
that invisible constraint is what scares me most, but as you've exemplified; writing it on line 2 as a comment makes it pretty clear that it has to be near the head of the file. That is satisfactory for me, thanks!

**Comment by evanunderscore** [comment]
I did have a thought previously that if you're specifically using a setuptools console_script, you could also include an entry_points key for argcomplete and have it examine that. That would save me having to go and find the file in #241.

**Comment by ava-dylang** [comment]
Would that work when the `argcomplete.autocomplete(argparse.ArgumentParser(...))` is invoked outside of the function indicated by console_scripts? I have a strong opinion that the argument parser should be stateless and always declare it as a constant at the top of my modules, like so:

```#!/usr/bin/env python3

""" Example argparser based python file
"""

import argparse

# import argcomplete

ARGP = argparse.ArgumentParser(
    description=__doc__,
    formatter_class=argparse.RawTextHelpFormatter,
)
ARGP.add_argument('--debug', action='store_true', help='Dump arguments')
# argcomplete.autocomplete(ARGP)


def main(argp=None):
    """ CLI Entry
    """
    if argp is None:
        argp = ARGP.parse_args()  # pragma: no cover

if __name__ == '__main__':
    main()  # pragma: no cover```

So I rely on the python script actually being executed (by witch I mean the module being loaded), This works currently with argcomplete, and I would hope this use case continues to work. /shrug
this is a tricky topic

**Comment by evanunderscore** [comment]
I'm not sure exactly what you mean. I'm talking about determining whether a module or package is argcomplete-compatible, which specifically has to be done without importing it, since importing arbitrary things could have undesirable side-effects. The part where the script is actually executed to do completion wouldn't be affected.
