### ISSUE TITLE
Example not working, maybe something improperly setup

### ISSUE THREAD

**Issue by treydock** [kislyuk/argcomplete#244]
I installed argcomplete 1.7.0 via RPM from EPEL and am unable to get the github example working:

```
$ ./describe_github_user.py --organization treydock --member <TAB>
<files in current directory listed>
```

I don't think I'm using the debug example correctly:

```
PROGNAME=./describe_github_user.py TEST_ARGS='--organization treydock --member t' _ARC_DEBUG=1 COMP_LINE="$PROGNAME $TEST_ARGS" COMP_POINT=31 _ARGCOMPLETE=1 $PROGNAME 8>&1 9>>~/autocomplete_debug.log
```

The log file is empty

I am using global completion and logged out and back in.

**Comment by kislyuk** [comment]
@treydock, I am unable to reproduce either of your problems.

Regarding the debug recipe you used, I personally find that debugging advice useless, and I just tried it and it failed for me too. I removed that advice from the readme, apologies for the confusion. However, if you use `export _ARC_DEBUG=1`, you should be able to see debug output from argcomplete when you press tab - if your completer shell hook is working, which it seems like it is not. If you could try to find whether your bash completion shell hooks are working properly, we may be able to debug this problem.

**Comment by kislyuk** [comment]
Closing due to lack of response.
