### ISSUE TITLE
Question: options acceptiong a comma-separated list

### ISSUE THREAD

**Issue by dedekind** [kislyuk/argcomplete#249]
Hi,

is there an easy way to complete options that accept a comma-separated list of names.
Say I have something like this in my tool:

tags = ["httpd", "redis", "nginx"]
parser.add_argument("--tags", metavar="TAGS", help=text)
argcomplete.autocomplete(parser)
args = parser.parse_args()

Now then I parse 'args.tags' manually, split, and turn into list in my tool.

This is what I want to achieve:

$ mytool --tags <tab>
  httd redis nginx
$ mytool --tags ngins,<tab>
  httd redis nginx
$ mytool --tags ngins,redis,<tab>
  httd redis nginx

... and so on ...

I have lots of other options in "mytool" and "autocomplete()" works well, but not for the above case.
I tried to explore the manual completer possibility, but did not find the way.

Any suggestion? Thanks!

**Comment by kislyuk** [comment]
Yes. You can complete comma-separated lists easily by writing a custom completer for the `--tags` argument. The completions will look like "nginx,redis,a nginx,redis,b ..." and so on.
