### ISSUE TITLE
Question: How to integrate with parent tool bash completion if the tool is a sub-command

### ISSUE THREAD

**Issue by electrofelix** [kislyuk/argcomplete#253]
I'm working on a project openstack/git-upstream and I recently discovered that at some point the bash auto-completion with argcomplete had stopped working. While fixing this I was looking to make various improvements to make sure that it would also support branch/ref name completion similar to git.

See https://review.openstack.org/582730/ for the current in progress patch.

I hit upon a few issues where it's not clear whether there is no better way or I'm doing something stupid (since I'm asking here you can guess that I tend to assume the latter until confirmed otherwise).

Firstly, being a sub-command of another tool appear to requires extensive manipulation of `bash complete` variables in order to wrap a call to `_python_argcomplete` and get the correct response returned to the parent complete calls. When a user runs `git-upstream` they can do using any of the following approaches
   - `git upstream <git-upstream-options>`
   - `git <git-options> upstream <git-upstream-options>`
   - `git-upstream <git-upstream-options>`

as being a sub-command of another is not a common requirement, it makes sense that the first 2 approaches to have `git` call `git-upstream` instead of it being called directly are a bit more complex and obviously that means hooking into `git`'s bash completion by defining a function called `_git_upstream`, it does seem in https://review.openstack.org/#/c/582730/1/bash_completion/git-upstream that I'm jumping through a lot of hoops to manipulate the `COMP_*` variables before calling `_python_argcomplete "git-upstream"` and I'm wondering if there isn't a better way of accomplishing this while still passing through all the correct info?

Secondly, it appears it's not possible to access the bash completion functions directly with subprocess even when using '/bin/bash -i' to ensure ~/.bashrc is sourced. I was trying to follow https://github.com/kislyuk/argcomplete/issues/76#issuecomment-38820489 and adapt it to call the function `__git_refs` from git's auto completion for bash as that would have been able to take into account any env vars or options set that would change the git directory to be used. Instead I would get undefined function. My workaround this is to use lines 29-30 in https://review.openstack.org/#/c/582730/1/bash_completion/git-upstream to perform extract the path and export it in before the python process is launched via `_python_argcomplete`. Is there a better way to access the parent bash env auto-complete functions? or is that solved based on an answer to the first query?

More than happy to submit a PR for what I'm doing to be a complex example if you think that would be useful for future users.

**Comment by evanunderscore** [comment]
Could you give a different parser to argcomplete based on whether you're being called as `git upstream` versus `git-upstream`? Completely untested, but something like:

```
parent = parser = argparse.ArgumentParser()
if sys.argv[0] == 'git':
    # No need to bother defining git flags since
    # argcomplete uses parse_known_args anyway.
    parser = parent.add_subparsers().add_parser('upstream')
parser.add_argument(...)
argcomplete.autocomplete(parent)
args = parser.parse_args()
```

If that doesn't fix your problem, let me know and I'll take a closer look when I get time.

**Comment by electrofelix** [comment]
@evanunderscore I had a quick look by dumping out the contents of sys.argv at https://github.com/openstack/git-upstream/blob/master/git_upstream/main.py#L126 and unfortunately although the program might be called on the CLI as `git -C .../ upstream` it's still invoked via `git-upstream` so there's no real way to determine from that approach.

But you did give me an idea, at the point that this is important, some of the `compgen|complete` related variables will have been set and I tested for their presence to determine whether to do this subparser idea.

```
    parent = parser = argparse.ArgumentParser(
        prog='git-upstream',
        description=__doc__.strip(),
        epilog='See "%(prog)s help COMMAND" for help on a specific command.',
        add_help=False)

    if 'COMP_LINE' in os.environ:
        import re
        if re.match("git .* upstream ", os.environ['COMP_LINE']):
            parser = parser.add_subparsers(
            ).add_parser('upstream', add_help=False)
```

Unfortunately this just seems to result in `upstream` being appended on each completion because it appears that to be some confusion on determining the next level of subcommand:

Running `COMP_LINE="git -C ../fixtures-git/ upstream " git -C ../fixtures-git upstream` outputs:
```
usage: git-upstream {upstream} ...

Command-line tool for tracking upstream revisions

positional arguments:
  {upstream}

See "git-upstream help COMMAND" for help on a specific command.
```

While subsequently running `COMP_LINE="git -C ../fixtures-git/ upstream " git -C ../fixtures-git upstream upstream` gets me the original help:
```
usage: git-upstream upstream [--version] [-h] [-q | -v] <command> ...

optional arguments:
  --version      show program's version number and exit
  -h, --help     show this help message and exit
  -q, --quiet    Suppress additional output except for errors, conflicts with
                 --verbose
  -v, --verbose  Increase verbosity from commands, conflicts with --quiet. May
                 be set more than once.

commands:
  <command>
    import       Import code from specified upstream branch.
    supersede    Mark a commit as superseded by a set of change-ids.
    help         Display help about this program or one of its commands.
    drop         Mark a commit as dropped.
```

I've experimented with injecting `git` into `sys.argv` ahead of the current command line just to see if it helps it understand to move onto the next level of subcommands in this case and unfortunately no joy.

Some of the pain around debugging this is definitely caused by the git bash completion hiding some of the responses when trying to use `_ARC_DEBUG` which is definitely not helping and I've yet to work out the source of that.

**Comment by evanunderscore** [comment]
You're right; when executed, `sys.argv` will always be whatever `git` gives you. However when run via argcomplete, it will instead examine `COMP_LINE`, which is why you need to pass the modified parser to `autocomplete`. You'll never be able to debug this by executing the command and observing what it returns, because `sys.argv` will never be what argcomplete actually looks at.

Are you sure your code that looks at `COMP_LINE` instead of `sys.argv` doesn't work for completion? You'll have to remove the work you've done that modifies those variables before passing it to the program.

**Comment by electrofelix** [comment]
I switched the bash completion that gets called by `git` to be:
```
_git_upstream() {
    if [[ -n "$_ARC_DEBUG" ]]
    then
        echo "COMP_LINE=${COMP_LINE}" >&2
        echo "COMP_WORDS=${COMP_WORDS[@]}" >&2
    fi
    
    _python_argcomplete "git-upstream"

    if [[ -n "$_ARC_DEBUG" ]]
    then
        echo "COMPREPLY=${COMPREPLY[@]}" >&2
    fi
}
```

I was only running it directly with `COMP_LINE` set to see what the parser put together as the command structure to explain why it kept seeing the next word as `upstream` rather than one of the subcommands at the next level `import`, `drop`, `supersede` or `help`.


When limiting it to `git upstream im` doing the double tab with that in place and the switch to inject a subparser I get the following
```
git upstream imCOMP_LINE=git upstream im
COMP_WORDS=git upstream im
COMPREPLY=import
port COMP_LINE=git upstream import 
COMP_WORDS=git upstream import 
COMPREPLY=import supersede help drop
COMP_LINE=git upstream import 
COMP_WORDS=git upstream import 
COMPREPLY=import supersede help drop

drop       help       import     supersede
```
which is initially correct, but then the next double tab doesn't show me the completion on the import subcommand, instead it behaves like it's just got 'git upstream' as the input and I see the following:
```
git upstream import <tab>COMP_LINE=git upstream import 
COMP_WORDS=git upstream import 
COMPREPLY=import supersede help drop
<tab>COMP_LINE=git upstream import 
COMP_WORDS=git upstream import 
COMPREPLY=import supersede help drop

drop       help       import     supersede
```

By comparison the tab completion on `git-upstream` gives me the following:
```
git-upstream import <tab><tab>
0.10.0         0.11.0         0.12.1         gerrit/master  origin/HEAD    zuul-conf      
0.10.1         0.12.0         0.9.0          master         origin/master
```

I've stuck up a gist https://gist.github.com/electrofelix/a77282312bcfc8eb1bcc1cd5a992aa03 of the local changes I've made on top of https://review.openstack.org/582730 just to make sure I've not made a mistake. Also added a second tweak to it in case the `add_help=False` on the parent when there was no explicit help options subsequent was causing some issues, but that's just checking it's not something about my argparse usage that's causing issues.

**Comment by kislyuk** [comment]
Closing due to lack of response.
