### ISSUE TITLE
Question: need access to parser.parse_args() or sys.arg from within custom completer

### ISSUE THREAD

**Issue by dougbdougb** [kislyuk/argcomplete#254]
I have multiple completer functions that build dynamic (on-demand) completion lists from a database and directory listing.  I also have some additional optional arguments that would affect the database and parent directory locations however it looks like from within a completer function I only have access to the current option/prefix or the default args to the parser as opposed to everything passed in thus far.  Am I missing something?  Below is a simple example of what I am trying

```
def myTagCompleter(prefix, parsed_args, **kwargs):
    if parsed_args.doIt:
        # this never works as parsed_args.doIt is always the default of False
        completeList = ['four','five','six']
    else:
        completeList = [‘one’,’two’,’three’]
    jobCompletion = [job for job in completeList if job.startswith(prefix)]
    return jobCompletion

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(-t, dest=tags, action=myTagValidater).completer = myTagCompleter
    parser.add_argument('-d', dest='doIt', default=False, action='store_true')

    argcomplete.autocomplete(parser)
    args = parser.parse_args()
```

```myScript.py -d -t f<tab>```

**Comment by evanunderscore** [comment]
That looks like it should work. Can you set `_ARC_DEBUG` and show me the output when you do that?

**Comment by kislyuk** [comment]
You do have access to everything parsed thus far via the parsed_args argument. Your example works for me.

If you are still experiencing the problem, please paste the complete script that reproduces it. What you pasted contains syntax errors and is not a complete Python argparse script (`python script.py --help` won't run).
