### ISSUE TITLE
Suggest using better (shorter) shebang line

### ISSUE THREAD

**Issue by kkew3** [kislyuk/argcomplete#259]
Hi. It appears to me that `register-python-argcomplete` script is generated automatically when installing via `pip`. The shebang line is set to the absolute path of the underlying python executable. However, when under a `virtualenv` environment, not only might the path contain spaces or special characters, but also it can grow so long that `# PYTHON_ARGCOMPLETE_OK` won't get parsed by `bash`. I suggest using `/usr/bin/env python` as shebang. Thanks.

**Comment by kislyuk** [comment]
Thanks for the suggestion. Unfortunately, using `/usr/bin/env python` is inappropriate as it will fail in many circumstances where multiple Python installations are present.

Your point about long paths and spaces in paths is good. I'll run some experiments to see what can be done about escaping spaces and potentially extending the 1KB scan limit to accommodate longer paths.

**Comment by kislyuk** [comment]
We don't really control the shebang line when pip installs the package. So there's nothing to do here.
