### ISSUE TITLE
Autocompletion for pip-installed scripts doesn't work when installation environment uses a exec-wrapped-in-python-docstring to avoid overlong shebang, e.g. in Spack package manager

### ISSUE THREAD

**Issue by mbdevpl** [kislyuk/argcomplete#265]
Hello! First of all, thank you so much for looking into the completion problems for scripts installed via pip (issue #241 and PRs #241 + #263)

Let me share my experience with the current master (i.e. commit 05b0817), where the changes addressing the problems are already merged. I think the pip-installed script completion was working sometime during the steps leading to the merge, but it was on a machine that I'm not using anymore, and unfortunately I can't reproduce the working state...

The below experience is from package called ingit (https://github.com/mbdevpl/ingit) I'm developing. FYI, the most recent version 0.4.7 on pypi has the changes described below, and they were implemented in mbdevpl/ingit@7cfb4eb, mbdevpl/ingit@afaa461 and mbdevpl/ingit@4424fc1.

The package in question has a console script `ingit`, as well as it is runnable via `python3 -m ingit`. Both methods lead to the same CLI. As mentioned in the title, the completion doesn't work now for the console script after installing with pip (i.e. `ingit <TAB>` won't work), but it works when it is completed via `python3 -m ingit <TAB>`.

Also, using `ingit <TAB>` registers the unwanted `complete -F _minimal ingit`, which I can remove via `complete -r ingit`. But when I try `eval $(python3 $(which register-python-argcomplete) ingit)`, nothing is registered.

What I'm using to enable completion is:

1. I have the output of `activate-global-python-argcomplete` in my `.bashrc` (not directly, but I checked that it definitely is added to my env)
2. I add `# PYTHON_ARGCOMPLETE_OK` in `__main__.py` of ingit package.
3. I use `argcomplete.autocomplete(parser)` and `... .completer = argcomplete.completers.ChoicesCompleter(choices=...)`.

I think the basic setup is correct, since the completion is working for the `python3 -m ingit`. Below is the pip-generated `ingit` script:

```
$ cat $(which ingit)
#!/bin/sh
'''exec' /home/mateusz/Software/Spack/opt/spack/linux-ubuntu19.04-x86_64/gcc-9.1.0/python-3.7.3-grshdmk5pfvfk5eku3hboj45y5zfpftw/bin/python3.7 "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys

from ingit.__main__ import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

As you can see, I'm using Python 3.7.3 built with GCC 9.1.0 on Ubuntu 19.04 x64, installed with Spack (https://github.com/spack/spack) package manager. The fact that I'm using Spack should be unrelated, because after all what happens with that is Python is built from source, so the end result is the same as with installing Python from source to a custom path.

Adding `# PYTHON_ARGCOMPLETE_OK` to either `__init__.py` or `main.py` of my package doesn't fix the problem. But adding the `# PYTHON_ARGCOMPLETE_OK` by hand into that above pip-generated `ingit` script fixes the problem.

My guess is that detection of the arcomplete marker is still not working after all and argcomplete is unable to find/resolve the `__main__.py` from the above script.

Do you have any suggestions what can I try to fix this?

**Comment by mbdevpl** [comment]
Also, after my slight modification in my fork of argcomplete mbdevpl/argcomplete@caa9e33, I can do the following, and get no output (i.e. no error):

```
$ python3 argcomplete/_check_console_script.py $(which ingit)
$
```

To confirm, I removed marker from `__main__.py` in my package and got the following:

```
$ python3 argcomplete/_check_console_script.py $(which ingit)
marker not found
$
```

Which means that the `_check_console_script.py` is actually able to correctly identify the `ingit` script. Nevertheless, the completion is not triggered for some reason.

**Comment by evanunderscore** [comment]
Thanks for the detailed report. There's a few things going on here.

Global completion isn't working because it is only applied to things with Python in the shebang line. Your generated script looks strange to me in that it uses `#!/bin/sh` followed by a separate line to exec Python. Do you know why it's being generated that way?

Explicitly registered completion did nothing because you forgot to quote your expression; it should be e.g. `eval "$(register-python-argcomplete ingit)"`. The fact that it doesn't produce any error appears to be an unfortunate side effect from when I added the `__python_argcomplete_run` helper and put a comment above it - since it's the first thing in the file, everything ends up being treated as a comment. I'll see if I can put something in to fix that.

Incidentally, you can run that helper as `python -m argcomplete._check_console_script` without having to patch anything.

**Comment by mbdevpl** [comment]
I see... Then I was wrong - in fact, it is exactly because of the Spack package manager that the bash completion is not working. The cause of altered shebang is Spack - it does this to protect from overlong shebang errors on some systems. To give you some context: spack is package manager aimed at high-performance computing systems, and used in increasing number of those systems. I'd say the main users are computational scientists and scientists from various fields executing some scientific workloads.

It looks like yet-another special handling (as with pyenv) might be needed for argcomplete to work with Python installed via Spack. I hope you could consider merging a pull request making this work. I'll try writing something now...

**Comment by mbdevpl** [comment]
I created #279 which addresses the issue above in my case.

**Comment by kislyuk** [comment]
Thanks for reporting this issue. I'm sorry but I don't see argcomplete being able to accommodate this situation - I've described the reasons in https://github.com/kislyuk/argcomplete/pull/279#issuecomment-569335241. I'm closing this issue; if you feel like something else needs to be done here, please provide a clear design rationale that addresses the reasons I listed and why it would be generally useful to include it in argcomplete.
