### ISSUE TITLE
git bash for Windows support

### ISSUE THREAD

**Issue by slanoe** [kislyuk/argcomplete#267]
Is it possible to use argcomplete with git bash for Windows ?

**Comment by kislyuk** [comment]
I'm not sure - I don't have it handy. What does `echo $BASH_VERSION` in that shell say?

**Comment by slanoe** [comment]
```4.4.23(1)-release```

**Comment by kislyuk** [comment]
That version has all the features necessary to support argcomplete. Are you having any specific issues using it?

**Comment by slanoe** [comment]
It's OK with WSL
Thanks

**Comment by evanunderscore** [comment]
I've revisited this and submitted draft PR #305 which provides some support for Git Bash.
