### ISSUE TITLE
🐚 xonsh support

### ISSUE THREAD

**Issue by anki-code** [kislyuk/argcomplete#271]
Hi! Thank you for argcomplete! It is great!

I use it in bash but now trying xonsh. Could you please help me to add [xonsh](https://xon.sh/) support? Xonsh has [Programmable Tab-Completion](https://xon.sh/tutorial_completers.html) for it and it's very short to understand.

1. Here the sample of function that calls when user type `<TAB>` anywhere and see `item1 item2` always:
```python
def sample_completer(prefix, line, begidx, endidx, ctx):
    '''
    prefix: the string to be matched (the last whitespace-separated token in the current line)
    line: a string representing the entire current line
    begidx: the index at which prefix starts in line
    endidx: the length of the prefix in line
    ctx: the current Python environment, as a dictionary mapping names to values
    return: options
    '''
    return {"item1", "item2"}
```

2. If user type 
```
python sample.py --argu<TAB>
                 ^17   ^23
``` 
then:
```python
prefix = "--argu"
line = "python sample.py --argu"
begidx = 17
endidx = 23
```

3. If you want to play with it just get the [xonsh.AppImage](https://github.com/niess/linuxdeploy-plugin-python/releases/download/continuous/xonsh-x86_64.AppImage) (`chmod +x xonsh.AppImage`) or `pip install xonsh` and run (just copy and paste in xonsh):
```
def sample_completer(prefix, line, begidx, endidx, ctx):
    return {"item1", "item2"}
	
completer remove sample_completer && completer add sample_completer sample_completer 
```

Could you please advise the best way to add argcomplete to xonsh?

If you can imagine some hacks like call `bash -c 'argcomplete(line)'` inside `sample_completer` it also would be interesting :)

**Comment by kislyuk** [comment]
Sorry, I don't think I'll be able to help with this.

**Comment by traverseda** [comment]
Does that mean pull requests welcome? Want to leave this issue open for discussion, even if you're not able to help with this yourself?

Are you also not able to offer advice to other people interested in implementing this, since they may not be familiar with argcomplete's internals?

**Comment by kislyuk** [comment]
I definitely welcome pull requests to this repo. This issue was specifically soliciting my (or argcomplete contributors') help. If you have specific questions about the internal architecture, feel free to ask here or open a new issue.

**Comment by anki-code** [comment]
@traverseda I've made [xontrib-argcomplete](https://github.com/anki-code/xontrib-argcomplete) as first try to solve this. Welcome to make a try :)
