### ISSUE TITLE
doc's link need to be fixed

### ISSUE THREAD

**Issue by SenZhangAI** [kislyuk/argcomplete#287]
at page <https://argcomplete.readthedocs.io/en/latest/#activating-global-completion>

link [see on Github](https://github.com/kislyuk/argcomplete/blob/master/argcomplete/bash_completion.d/python-argcomplete.sh) will return 404 at this moment,

That is caused by the file name of `argcomplete.sh` changed to `argcomplete`

**Comment by kislyuk** [comment]
That is not the current location of the docs. Added a workaround to rewrite the docs on RTD.
