### ISSUE TITLE
fish 3.1: test_special_characters_double_quoted (test.test.TestFish) ... unexpected success

### ISSUE THREAD

**Issue by hroncok** [kislyuk/argcomplete#290]
Since we have updated fish to 3.1 in Fedora, the package fails to build with:

```
test_special_characters_double_quoted (test.test.TestFish) ... unexpected success
```

I know how to fix this for us, by removing the test from:

https://github.com/kislyuk/argcomplete/blob/d2c12c3bfca2f1f11ad0737462360fba035fa71d/test/test.py#L1250-L1255

But I have no idea how to make it xfail only with fish 3.0.

**Comment by evanunderscore** [comment]
How about this?

```
 class TestFish(_TestSh, unittest.TestCase): 
     expected_failures = [ 
         'test_parse_special_characters', 
         'test_comp_point', 
     ] 
    if get_fish_version_somehow() > (3, 1):
        expected_failures.extend([
            'test_special_characters_double_quoted',
        ])

**Comment by hroncok** [comment]
Sure, do we have a rady `get_fish_version_somehow`? I am not familiar with fish at all.

**Comment by evanunderscore** [comment]
Neither am I, but I would imagine it would be an environment variable like in bash: https://github.com/kislyuk/argcomplete/blob/d2c12c3bfca2f1f11ad0737462360fba035fa71d/test/test.py#L29. I don't have an environment handy at the moment to try the same for fish.

**Comment by hroncok** [comment]
```
$ fish -c 'echo $FISH_VERSION'
3.1.0
```

**Comment by hroncok** [comment]
```pycon
>>> FISH_VERSION = subprocess.check_output(['fish', '-c', 'echo $FISH_VERSION']).decode().strip()
>>> FISH_VERSION_TUPLE = tuple(int(i) for i in FISH_VERSION.split('.'))
>>> FISH_VERSION_TUPLE >= (3, 1)
True
```

**Comment by evanunderscore** [comment]
Looks good to me. Would you like to submit a pull request?

**Comment by hroncok** [comment]
I won't get to it soon, sorry.

**Comment by evanunderscore** [comment]
Should be fixed, let me know if you're still having issues.
