### ISSUE TITLE
Request to use code from argcomplete

### ISSUE THREAD

**Issue by dan1994** [kislyuk/argcomplete#294]
Hey there,

As a zsh user, I wanted a better solution than using `bashcompinit`, and after going over [this issue](https://github.com/kislyuk/argcomplete/issues/10) and learning about `compsys` (the completion system of zsh), I decided it would currently be easier to write something of my own then integrating zsh support into argcomplete.

Having decided so, I started developing [pyzshcomplete](https://github.com/dan1994/pyzshcomplete), which tries to be as similar as possible to argcomplete's interface as possible (and can potentially be used together with argcomplete in the same script).

There are several challenges that I see no reason to overcome myself as argcomplete already solves them well. In particular, the code that finds the magic `PYTHON_ARGCOMPLETE_OK` in general and more specifically in modules.

I wanted to politely ask to use this code. Assuming that would be alright, should I add a copyright notice somewhere, and if so where and in what format?

P.S.: I use an MIT license.

**Comment by kislyuk** [comment]
Hi, thanks for your interest. You are welcome to reuse the code as long as you comply with the terms of the Apache 2 license. The license specifies the format in which the notice should be given.

**Comment by dan1994** [comment]
Thanks! I'll figure out the formalities.

BTW, thanks for the awesome project. It inspired me to start my own, and I use a lot of your methodology to provide such a plug and play solution for users.
