### ISSUE TITLE
Question: can you adjust the sorted output?

### ISSUE THREAD

**Issue by yoyoyopcp** [kislyuk/argcomplete#298]
Currently, autocompleted flags and positional args are mixed like so:

```# mycommand <TAB><TAB>
A:root          --cli           --file-system   foo:root        --help
```

Is there a way to have flagged options appear before positional args, like so?

```# mycommand <TAB><TAB>
A:root     foo:root        --cli           --file-system        --help
```

**Comment by evanunderscore** [comment]
The sorting you're seeing is coming from Bash (see https://unix.stackexchange.com/questions/215937/disable-sorting-of-compreply-in-bash-complete-function).

You can disable this when you run `activate-global-python-argcomplete` or `register-python-argcomplete` with `--complete-arguments -o nosort`, noting that this overrides argcomplete's default options so you should additionally specify those.

Examples:

```
eval "$(activate-global-python-argcomplete --dest=- --complete-arguments -o default -o bashdefault -o nosort)
eval "$(register-python-argcomplete test/prog --complete-arguments -o nospace -o default -o bashdefault -o nosort)"
```

With this set, you'll start seeing the actual ordering returned by argcomplete, however I don't believe there are any configuration options to change it. In the case of the test program `test/prog`, I see the flags `-h` and `--help` first, then the list of subcommands in the order they are defined on the parser.

You could potentially subclass CompletionFinder and override collect_completions or a similar function if you wanted to modify this yourself.

**Comment by yoyoyopcp** [comment]
@evanunderscore thank you so much!  I highly appreciate this.
