### ISSUE TITLE
The testing requires /usr/bin/python to be present

### ISSUE THREAD

**Issue by scarabeusiv** [kislyuk/argcomplete#299]
As per above when you execute tests only with python3 available in the enviroment quite few of the tests will fail as the prog command calls /usr/bin/env python.

I think the tests should use sys.executable and prefix it where needed to make sure you actually use the python interpreter which is used to spawn the testing enviroment.

**Comment by evanunderscore** [comment]
Thanks for the report. As described in #255, it's unfortunately not as simple as just using sys.executable. Please comment on that issue if you have anything to add.

**Comment by evanunderscore** [comment]
By the way, the tests should always work from within a virtual environment, where `python` will always refer to the correct Python version. If you have restrictions that prevent you from using virtual environments, please add them to #255 so we can make sure our eventual solution works for your use case.
