### ISSUE TITLE
argcomplete does not work with aws-vault

### ISSUE THREAD

**Issue by Gim6626** [kislyuk/argcomplete#304]
I've got custom Python script and added `argcomplete` to it using instructions from https://kislyuk.github.io/argcomplete/. One note - I need to call it using `aws-vault` cause my script works with Amazon and I need credentials setup before script logic work.

If I call my `lptl.py` directly autocomplete works:
```
$ python3 lptl.py --
--ansible-repo-path    --help                 --skip-app-start       --test-slaves-count
--app-version          --servers-list         --test-environment     --test-slaves-ips
--config               --show-test-plan-only  --test-scenario-name   
--debug                --skip-app-deploy      --test-scenario-path
```

But when I call it with wrapper, it is not, pressing TAB after following command line results to nothing:
```
$ aws-vault exec shared-test-full -- python3 lptl.py --
```

Could anybody help solving this issue?

BTW, I use macOS.

P.S.: Also I've got virtualenv, don't know if it affects, but I installed `argcomplete` both to local and global environments.

**Comment by evanunderscore** [comment]
It's possible the wrong version of Python is being used to look up the script associated with the command line wrapper. Can you set `_ARC_DEBUG=1` and paste the output from a failed tab completion attempt please?

**Comment by Gim6626** [comment]
I've set `export _ARC_DEBUG=1` and in same shell tried again to get autocompletion - now output

**Comment by Gim6626** [comment]
Then I tried to test more simple script without many dependencies like in mine:
```
#!/usr/bin/env python3
# PYTHON_ARGCOMPLETE_OK
import argparse
import argcomplete

parser = argparse.ArgumentParser(description='Test script')
parser.add_argument('-d',
                    '--debug',
                    help='Debug mode')
argcomplete.autocomplete(parser)
cmd_line_args = parser.parse_args()
print(cmd_line_args.debug)
```

When I try to autocomplete `python3 test.py --` I get:
```
$ python3 test.py --word -- split, lexer state: 'None'

LINE: 'python3 test.py --' 
POINT: 18 
PREQUOTE: '' 
PREFIX: '--' 
SUFFIX: '' 
WORDS: ['test.py']
Active parsers: [MonkeyPatchedIntrospectiveArgumentParser(prog='test.py', usage=None, description='Load&performance Tests Launcher', formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)]
Visited positionals: [MonkeyPatchedIntrospectiveArgumentParser(prog='test.py', usage=None, description='Load&performance Tests Launcher', formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)]
invoking parser with []
parsed args: (Namespace(debug=None), [])
all active parsers: [MonkeyPatchedIntrospectiveArgumentParser(prog='test.py', usage=None, description='Load&performance Tests Launcher', formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)]
active_parser: MonkeyPatchedIntrospectiveArgumentParser(prog='test.py', usage=None, description='Load&performance Tests Launcher', formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)
optional options: ['--help', '--debug']
next_positional: None
Active actions (L=0): []
active options: ['--help', '--debug']
display completions: {'--help': 'show this help message and exit', '--debug': 'Debug mode'}

Returning completions: ['--help', '--debug']
```

It's good I think.

Then I tried to call Python with AWS wrapper - `$ aws-vault exec shared-test-full -- python3 test.py --` - nothing.

Maybe with such wrapper argcomplete was not called at all?

**Comment by kislyuk** [comment]
argcomplete does not generally work with arbitrary command line wrappers. To understand why, check the section of the documentation describing the protocol (https://kislyuk.github.io/argcomplete/#argcomplete-autocomplete-parser). When you run your command through a wrapper, the wrapper must be aware of the argcomplete protocol (in particular, it must forward fd 8 to the wrapped subprocess). I don't think it's possible to make argcomplete work with this utility.

**Comment by Gim6626** [comment]
Solved by incapsulating `aws-vault` call into Python script. Now autocompletion works fine.
