### ISSUE TITLE
How to write ZSH completion function in Python

### ISSUE THREAD

**Issue by blueray453** [kislyuk/argcomplete#315]
I am getting started with this project so I apologize for such a basic question.

For example the following is a zsh completion function for command `foo`:

```
#compdef _foo foo
compadd first second third fourth
```

So, if we type `foo <tab>` in the zsh terminal, it suggests first second third fourth.

How can I do this using argcomplete?

**Comment by evanunderscore** [comment]
This is not a generic utility for implementing tab completion; it automatically generates tab completion for a program you have implemented in Python using argparse. You can follow the example in the readme to [create a script](https://github.com/kislyuk/argcomplete/blob/6d33c8e321ffa388c879fec56a80add0181f56b8/README.rst#synopsis) and then [register it for completion in zsh](https://github.com/kislyuk/argcomplete/blob/6d33c8e321ffa388c879fec56a80add0181f56b8/README.rst#zsh-support). You would have to learn how to express your desired command line syntax using [argparse](https://docs.python.org/3/library/argparse.html).

**Comment by blueray453** [comment]
Thank you very much for this kind reply.
