### ISSUE TITLE
importlib-metadata 2.0 support

### ISSUE THREAD

**Issue by nicoddemus** [kislyuk/argcomplete#321]
Hi,

The requirement for importlib-metadata is pinned to <2 on `master`:

https://github.com/kislyuk/argcomplete/blob/9df5bcb635be8b6b46725dad136300a0c07824f6/setup.py#L8

I assume that is (wisely) pinned to <2 avoid a regression due to a major `importlib-metadata` release.

`importlib-metadata 2.0` has been released yesterday, so I was wondering if support for that version can be tested and a new release made?

**Comment by kislyuk** [comment]
Thanks for reporting. Fix released in v1.12.1, please test.

**Comment by scpeters** [comment]
> Thanks for reporting. Fix released in v1.12.1, please test.

works for me; thanks!

**Comment by scpeters** [comment]
importlib-metadata just released 3.0; should I open a new issue for that? I believe requiring python 3.6 is the only change from 2.0

* https://github.com/python/importlib_metadata/blob/v3.0.0/docs/changelog.rst#v300

**Comment by kislyuk** [comment]
Released in v1.12.2
