### ISSUE TITLE
register-python-argcomplete  in WSL is using windows python rather than WSL python

### ISSUE THREAD

**Issue by rnwolf** [kislyuk/argcomplete#324]
I am installing pipx in my WSL/Ubuntu environment.  I am using zsh shell.
The following lines ate in my .zshrc file:

```
# Enable completions for pipx in zsh
autoload -U bashcompinit
bashcompinit
#Afterwards you can enable completion for pipx
eval "$(register-python-argcomplete pipx)"
``` 

When opening up my zsh shell in Windows Terminal I get the following message:

```
-- console output produced during zsh initialization follows --

/home/rnwolf/.zshrc:150: /mnt/c/Users/rnwol/AppData/Roaming/Python/Python38/Scripts/register-python-argcomplete: 
bad interpreter: C:\Users\rnwol\AppData\Local\Programs\Python\Python38\python.exe^M: no such file or directory
```

Seems like `register-python-argcomplete` is finding the windows python, rather than the WSL python?

In zsh I use pyenv to install and specify what python to use.

```
❯ where python
/home/rnwolf/.pyenv/shims/python
```

Any suggestions?

**Comment by evanunderscore** [comment]
What happens when you run `register-python-argcomplete` manually from within zsh? [The script isn't doing anything clever](https://github.com/kislyuk/argcomplete/blob/a93a4f4dc785373f320d168d2d5a1a11bdc50315/scripts/register-python-argcomplete), though I've seen pip/easy_install mess with shebang lines before.

**Comment by rnwolf** [comment]
I het the following

```
❯ register-python-argcomplete
zsh: /mnt/c/Users/rnwol/AppData/Roaming/Python/Python38/Scripts/register-python-argcomplete: bad interpreter: C:\Users\rnwol\AppData\Local\Programs\Python\Python38\python.exe^M: no such file or directory
usage: register-python-argcomplete [-h] [--no-defaults] [--complete-arguments ...] [-s {bash,tcsh,fish}]
                                   [-e EXTERNAL_ARGCOMPLETE_SCRIPT]
                                   executable [executable ...]
....   more help text here
```

I have found this zsh plugin for pipx, which seems to do the job.
Installed as follows.
``git clone https://github.com/thuandt/zsh-pipx $ZSH_CUSTOM/plugins/zsh-pipx```

**Comment by rnwolf** [comment]
This is a MS-Windows WSL issue.

https://dillieodigital.wordpress.com/2018/01/05/how-to-fix-path-conflicts-in-wsl-bash-on-ubuntu-on-windows/

"What’s happening is that when WSL starts up, the default environment setup adds all of the windows paths into the environment path. I suspect this is to help you get access to some of your tools (like Visual Studio Code) from both environments, but it can cause conflicts. if you type “echo $PATH” you’ll see what I mean:"


When I look for ` register-python-argcomplete` in my WSL zsh shell:

```
❯ where register-python-argcomplete
/mnt/c/Users/rnwol/AppData/Roaming/Python/Python38/Scripts/register-python-argcomplete
/home/rnwolf/.local/bin/register-python-argcomplete
/home/rnwolf/.local/bin/register-python-argcomplete
```
You see that the "Windows" version of the file is listed first.  
The solution suggested did not work for me.

I ended up with the following in my .zshrc , but it did not work.  
```
PATH=$(echo :$PATH: | sed -e 's,:/mnt/c/Users/rnwol/AppData/Roaming/Python/Python../Scripts/:,:,g' -e 's/^://' -e 's/:$//' -e 's,:/mnt/c/Users/rnwol/AppData/Local/Programs/Python/Python../Scripts:,:,g')
```
In the end all I did was call the linux version of the script directly in my .zshrc

```
# Enable completions for pipx in zsh
autoload -U bashcompinit
bashcompinit
#Afterwards you can enable completion for pipx
eval "$(/home/rnwolf/.local/bin/register-python-argcomplete pipx)"
```

Now Tab completion works.
