### ISSUE TITLE
autocomplete in csh not working 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [kislyuk/argcomplete#341]
I tried to register my program with tcsh and it didn't work, after following the direction autocomplete works on zsh, bash but not tcsh in my Mac system

```
(buildtest) [DOE-7086392:~/Documents/buildtest] siddiq90% eval `register-python-argcomplete --shell tcsh buildtest`
(buildtest) [DOE-7086392:~/Documents/buildtest] siddiq90% buildtest <TAB>
(buildtest) [DOE-7086392:~/Documents/buildtest] siddiq90% echo $SHELL
/bin/csh
(buildtest) [DOE-7086392:~/Documents/buildtest] siddiq90% $SHELL --version
tcsh 6.21.00 (Astron) 2019-05-08 (x86_64-apple-darwin) options wide,nls,dl,bye,al,kan,sm,rh,color,filec
```

The version of arcomplete is the following

```
(buildtest) [DOE-7086392:~/Documents/buildtest] siddiq90% pip list | grep argcomplete
argcomplete                   1.12.2
(buildtest) [DOE-7086392:~/Documents/buildtest] siddiq90% python --version
Python 3.7.3
```

Any idea whats the issue?

**Comment by evanunderscore** [comment]
Thanks for the report. Can you please export `_ARC_DEBUG=1` and paste the output of attempted tab completion?

**Comment by shahzebsiddiqui** [comment]
i dont see any output 
```
(buildtest) [DOE-7086392:~/Documents/buildtest] siddiq90% setenv _ARC_DEBUG 1
(buildtest) [DOE-7086392:~/Documents/buildtest] siddiq90% echo $_ARC_DEBUG
1
(buildtest) [DOE-7086392:~/Documents/buildtest] siddiq90% eval `register-python-argcomplete --shell tcsh buildtest`
(buildtest) [DOE-7086392:~/Documents/buildtest] siddiq90% buildtest <TAB>
```

**Comment by evanunderscore** [comment]
Are you able to try again with the change in #342?

**Comment by shahzebsiddiqui** [comment]
ill test it once there is new release. Sorry bit overwhelmed right now.

**Comment by evanunderscore** [comment]
No problem at all. I'm not in any rush, just trying to help resolve your issue whenever you have the time.

**Comment by kislyuk** [comment]
Thank you for your interest in argcomplete. csh is not supported by the maintainers and is only supported by contributors. To help focus maintenance, I will be closing this issue now; please feel free to continue discussion if you have additional information.
