### ISSUE TITLE
how to use FilesCompleter from a base dir

### ISSUE THREAD

**Issue by nadavhalahmi** [kislyuk/argcomplete#368]
for example:
`parser.add_argument('--file').completer = FilesCompleter('/home')`
will show all directories/files in /home

**Comment by evanunderscore** [comment]
I don't believe this is a supported feature of FilesCompleter; it only seeks to replicate ordinary command line file completion, either absolute or relative to the working directory. If you want to complete filenames from a specific directory, you will need to either modify the completer or implement your own as a custom completer.
