### ISSUE TITLE
installation instructions do not work for me (zsh: command not found)

### ISSUE THREAD

**Issue by bd** [kislyuk/argcomplete#372]
As per the installation instructions in the README, I ran 
```
pip3 install argcomplete
activate-global-python-argcomplete
```
but this results in `zsh: command not found: activate-global-python-argcomplete`

so at a minimum, it might be useful to expand the docs on troubleshooting installation.

This is a 2019 MBP (intel) on OSX 12.4

**Comment by kislyuk** [comment]
Thank you for your interest in argcomplete. Your installation environment appears broken, since scripts installed by Python packages don't seem to appear on your PATH.
