### ISSUE TITLE
Can't get argcomplete to work for rdiff-backup

### ISSUE THREAD

**Issue by ericzolf** [kislyuk/argcomplete#375]
I'm probably too stupid to make it work, or my usage of argparse isn't standard enough (my current suspicion), but I could use a hunch where to start looking:

1. my changes to introduce argcomplete are at https://github.com/rdiff-backup/rdiff-backup/compare/master...ericzolf-fix-new-autocomplete-725 and quite overseeable (and IMHO according to docs)
2. I've made sure that the old bash completion is deactivated, then installed new version via `pip install .` in the Git repo
3. after that I've called `eval $(register-python-argcomplete rdiff-backup)` in the current shell
4. but `rdiff-backup <TAB>[<TAB>]` doesn't produce anything
5. adding `_ARC_DEBUG=1` shows that argcomplete is active but it only shows the error message you get when you call `rdiff-backup` without any argument i.e. `rdiff-backup: error: Action backup requires 2 location(s) instead of [].` preceded by a summary of old options.

Sorry to report this as an issue but I couldn't find any forum or mailing list, hope this is OK.

**Comment by evanunderscore** [comment]
This appears to have been solved separately, and the linked branch is no longer available. Sorry we didn't get to this when it was still relevant. Please feel free to open a new issue if you need help in future.
