### ISSUE TITLE
Typings?

### ISSUE THREAD

**Issue by tony** [kislyuk/argcomplete#377]
Interested in typings?

Downstream this would make completions nicer and let users check argcomplete usage for correctness

(I am happy to contribute them, if so.)

**Comment by kislyuk** [comment]
Hi, thanks for the note. Yes, type hint contributions are welcome (as long as they are added to the code and not as separate stub files, which are hard to maintain).

**Comment by tony** [comment]
> Hi, thanks for the note. Yes, type hint contributions are welcome (as long as they are added to the code and not as separate stub files, which are hard to maintain).

Bikeshed: do you have a preference for the way its imported?

via a short namespace (e.g. [flask style](https://github.com/pallets/flask/blob/2.2.2/src/flask/app.py#L7), [2](https://github.com/pallets/flask/blob/2.2.2/src/flask/app.py#L1065-L1070)):
```python
import typing as t


def fn(val; str, items: t.List[str]):
    ...
```

vs

```python
from typing import List


def fn(val; str, items: List[str]):
    ...
```

In my libs I ended up picking flask's style: `import typing as t`.

**Comment by kislyuk** [comment]
No preference - feel free to use either style.
