### ISSUE TITLE
pytest?

### ISSUE THREAD

**Issue by tony** [kislyuk/argcomplete#383]
@kislyuk Are you willing to have a PR for test/test.py rewritten in `py.test` style?

`py.test` would make the tests way more cleaner than [`unittest`](https://docs.python.org/3/library/unittest.html)

I switched from `unittest` to py.test on my projects years ago and its excellent:

- https://github.com/tmux-python/tmuxp/pull/151/files, example: [unittest](https://github.com/tmux-python/tmuxp/blob/2fab3a08b19ec38016da6c51a434f190a94b10ed/tests/test_workspacebuilder.py) vs [pytest](https://github.com/tmux-python/tmuxp/blob/2fab3a08b19ec38016da6c51a434f190a94b10ed/tests/test_workspacebuilder.py)

**Comment by kislyuk** [comment]
Thanks, but no, we are fine with unittest.

**Comment by tony** [comment]
@kislyuk Will you go into this a bit more? Any concerns I can address? (Think it'd add complication packaging / test wise or be more harm than good, somehow?)

FYI I'm not unbiased, I'll admit I'm pro-py.test

**Comment by kislyuk** [comment]
I prefer to use standard library packages unless there is a very good reason not to. I don't see anything wrong with unittest, I disagree that it makes the tests cleaner, and I find the pytest fixtures loading system (especially autoload fixtures and the shadow fixture namespace) to be opaque and unintuitive to the point where I get very frustrated with pytest as a whole.

**Comment by tony** [comment]
> and I find the pytest fixtures loading system (especially autoload fixtures and the shadow fixture namespace) to be opaque and unintuitive to the point where I get very frustrated with pytest as a whole.

yes pytest employs magic.

It is still possible to create an impenetrable web of autouse fixtures and make testing impossible. I've forgotten the times I've experienced this - I've since changed to using `autouse=True` very conservatively and keep fixtures in a root `conftest.py`. I also avoid [pytest markers](https://docs.pytest.org/en/7.1.x/how-to/mark.html#mark) - the side effect is too hard to trace.

[Test collection](https://docs.pytest.org/en/7.1.x/example/pythoncollection.html) in pytest is indeed complex, especially if [`@pytest.fixture`](https://docs.pytest.org/en/7.1.x/reference/reference.html?highlight=pytest%20fixture#pytest.fixture)'s [`autouse=True`](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#autouse-fixtures-fixtures-you-don-t-have-to-request) has side effects impinging on test runs. [Fixture availability](https://docs.pytest.org/en/7.1.x/reference/fixtures.html#fixture-availability) is intuitive - based on module depth, for the most part - [`conftest.py(s)`](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#overriding-fixtures-on-various-levels) being a critical aspect of most test suites - but the benefit is it makes it easy to search for the file and find where the fixtures are at by checking adjacent (then traversing up directories) from the test file.
