### ISSUE TITLE
Drop python 3.6?

### ISSUE THREAD

**Issue by tony** [kislyuk/argcomplete#387]
In regards to python 3.6 mentioned throughout the codebase (README, CI)

- Released 5 years and 10 months ago (22 Dec 2016)
- Support Ended 10 months ago (23 Dec 2021)

Source: https://endoflife.date/python

Proposal:
- Remove python 3.6
- Remove any python 2 / < 3.7 compat related code for cleanliness

**Comment by kislyuk** [comment]
Python 3.6 is not supported and mention of support for it has been removed. The process of cleaning up Python 2 specific code is mostly complete.
