### ISSUE TITLE
Support mypy type annotations aka PEP 484

### ISSUE THREAD

**Issue by SchoolGuy** [kislyuk/argcomplete#396]
Currently when using `mypy` as a static type checker you must add this project to the ignore list.

The message looks a bit like this:

```
Run python -m mypy <module>
<module>/cli.py:35: error: Skipping analyzing "argcomplete": module is installed, but missing library stubs or py.typed marker  [import]
```

More information on how to add this to a project and fix the warning can be found [here](https://mypy.readthedocs.io/en/stable/).

**Comment by SchoolGuy** [comment]
This might be fixed by #378

**Comment by tony** [comment]
I can take a closer look at this over the coming weeks ☝️. Thank you for bringing it up

We also have #377

**Comment by SchoolGuy** [comment]
This is a duplicate of #377. Thus closing this Issue.
