### ISSUE TITLE
Recommended replacement for `split_line`?

### ISSUE THREAD

**Issue by blink1073** [kislyuk/argcomplete#419]
Thanks for this library!  We're using it `ipython/traitlets`, and were relying to the top level [`split_line`](https://github.com/ipython/traitlets/blob/458b12102e945cbfc18a9e9126619f6d9d7a49b5/traitlets/config/argcomplete_config.py#L48) that was removed in #414.  I noticed in the tests that you're still using the private `_split_line`.  Do you have a recommended replacement for using that function directly?

**Comment by kislyuk** [comment]
OK, split_line is back in v3.0.3. I'm happy to keep it in the API but will probably eventually move it to `argcomplete.lexers.split_line` to keep the top level namespace minimal and ergonomic.

**Comment by blink1073** [comment]
Thank you!
