### ISSUE TITLE
installing zsh globally adds paths to completion options introduced in v3.1.4

### ISSUE THREAD

**Issue by maurerle** [kislyuk/argcomplete#458]
When installing `argcomplete >= v3.1.4` globally, the default folder and file options are added (additionally to the useful completions).

```bash
(myenv) ➜  MYPROJECT git:(main) ✗ project --loglevel
myproject/        docker_configs/           LICENSES/               
logfile           Dockerfile                poetry.lock             
cli.py            docs/                     __pycache__/            
dist/             export/                                           
CRITICAL  WARNING  ERROR                                                    
NOTSET    FATAL    DEBUG  WARN  INFO  -- logging level used for file log 
```

#### Older Version and non-global works fine

pip install argcomplete==v3.1.3` and installing the tab completion, everything works fine.

So the fix here is probably missing something:
https://github.com/kislyuk/argcomplete/commit/afdf75bc6f43f1d1584468665ea1147c22b9767c

**Comment by evanunderscore** [comment]
Fixed in #463. Thanks for reporting!
