### ISSUE TITLE
Contributing guidelines for argcomplete?

### ISSUE THREAD

**Issue by truthdoug** [kislyuk/argcomplete#460]
The [contributing guidelines link](https://github.com/kislyuk/.github/blob/285af23c84e899411496dcd2c30b3f386f0f3a98/CONTRIBUTING.md) for argcomplete goes to a page seemingly unrelated to this project. It refers to `script/bootstrap` and `script/cibuild` that don't exist in argcomplete.

Are there more argcomplete-specific contribution guidelines? I'd like to submit a PR

**Comment by kislyuk** [comment]
Sorry, that's some generic boilerplate that I'll need to update. Thanks for pointing it out.

There are no specific contributing guidelines aside from "be nice", "discuss your idea before writing lots of code" and "add tests for your changes". Please feel free to open a PR.

**Comment by kislyuk** [comment]
OK, I went ahead and updated the code of conduct and contributing guidelines so they now apply to the project with no reservations.
