### ISSUE TITLE
Unable to get completion to work for NetExec

### ISSUE THREAD

**Issue by Adamkadaban** [kislyuk/argcomplete#468]
I haven't been able to get this working for https://github.com/Pennyw0rth/NetExec

This is what the default output is of running without arguments:
![image](https://github.com/kislyuk/argcomplete/assets/34610663/53776dd5-c034-48d2-8cb3-15741b3f0b1f)

Syntax is `nxc <protocol> <subargs>`

Diff File:

```diff
diff --git a/nxc/cli.py b/nxc/cli.py
index 29fd91f8..c815017e 100755
--- a/nxc/cli.py
+++ b/nxc/cli.py
@@ -1,4 +1,5 @@
 import argparse
+import argcomplete
 import sys
 from argparse import RawTextHelpFormatter
 from nxc.loaders.protocolloader import ProtocolLoader
@@ -85,6 +86,7 @@ def gen_cli_args():
         parser.print_help()
         sys.exit(1)
 
+    argcomplete.autocomplete(parser)
     args = parser.parse_args()
 
     if args.version:
diff --git a/pyproject.toml b/pyproject.toml
index ef0f03bd..4ff77a1b 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -65,6 +65,7 @@ resource = "^0.2.1"
 oscrypto = { git = "https://github.com/Pennyw0rth/oscrypto" } # Pypi version currently broken, see: https://github.com/wbond/oscrypto/issues/78 (as of 9/23)
 pyreadline = "^2.1" # for the build - impacket imports its hidden from the builder so an error occurs
 ruff = "=0.0.292"
+argcomplete = "3.2.1"
 
 [tool.poetry.group.dev.dependencies]
 flake8 = "*"
@@ -123,4 +124,4 @@ target-version = "py37"
 [tool.ruff.flake8-quotes]
 docstring-quotes = "double"
 inline-quotes = "double"
-multiline-quotes = "double"
\ No newline at end of file
+multiline-quotes = "double"
```

I did `eval "$(register-python-argcomplete nxc)"` and `eval "$(register-python-argcomplete netexec)"`  separately to see if it was an issue with naming.

When I export `_ARC_DEBUG`, it seems to run the program twice but doesn't parse any of the options.

I think this may be because of the subcategories for the tool (eg. `nxc smb` and `nxc ssh`). Is there a way to set up custom parsing for this?

Thanks

**Comment by evanunderscore** [comment]
At a glance I would guess this is your problem:

https://github.com/Pennyw0rth/NetExec/blob/ef4f2df92cc553274a09c38fead0030d5018481e/nxc/cli.py#L84-L86

We don't actually invoke your program with arguments, so you'll quit before generating completions. If moving `argcomplete.autocomplete(parser)` above this doesn't fix your problem, please show the output of attempted tab completion with `_ARC_DEBUG=1`.

**Comment by Adamkadaban** [comment]
Oh wow, that was a simple solution.

Thanks for the help! @evanunderscore
