### ISSUE TITLE
No automatic testing on windows?

### ISSUE THREAD

**Issue by mauvilsa** [kislyuk/argcomplete#479]
I have some unit tests that check the integration of argcomplete in jsonargparse. Since last week the tests using python 3.11 on windows started failing, see for example https://github.com/omni-us/jsonargparse/actions/runs/8575212908/job/23535242709. For all other python versions it works fine. I don't really understand what is going wrong.

But anyway, I came to this repo to see if the tests on windows were also failing. But there seems to be only tests on ubuntu and macos, e.g. https://github.com/kislyuk/argcomplete/actions/runs/8197350911/job/22419192361. Is it correct that there is no automatic testing on windows?

**Comment by kislyuk** [comment]
Correct. This project does not provide direct Windows support (Windows provides WSL, which is the recommended way to make use of argcomplete on Windows). Contributors have maintained support for Powershell and Windows in general in the `contrib` directory.

**Comment by kislyuk** [comment]
From the log outputs of your tests, it does look like Python 3.11.9 may have introduced argparse API changes that may affect argcomplete functionality. I've opened a separate issue https://github.com/kislyuk/argcomplete/issues/481 to track this.
