### ISSUE TITLE
autocompletion is slow and stuck

### ISSUE THREAD

**Issue by YanivDorGalron** [kislyuk/argcomplete#484]
autocompletion takes too much time on moba-xterm and stucks my cli
any tips on what to do in that case?
takes at least 5 seconds for each completion

**Comment by kislyuk** [comment]
Thanks for your interest in argcomplete. Based on the information you provided, this does not seem like an issue with argcomplete, so I'm going to close it for now.

You may want to read the documentation for this project about what to do in a situation that you encountered, or provide a complete reproduction test case.

**Comment by YanivDorGalron** [comment]
Im sorry I didn't noticed it.
Thank you for the reply!
