### ISSUE TITLE
csh/tcsh support (I've got a hack working)

### ISSUE THREAD

**Issue by redstreet** [kislyuk/argcomplete#49]
I had to get argcomplete working on tcsh. I have a hack working. It would be great if it could get integrated properly into argcomplete. I'll work on this later if I can. I'm using tcsh 6.17.00. Here's what I do, to get an example called 'newcommand.py' working:

#### file: newcommand-complete.sh

```
#!/bin/sh
export IFS=''
export COMP_LINE=${COMMAND_LINE}
export COMP_WORDBREAKS=
export COMP_POINT=${#COMMAND_LINE}
export _ARGCOMPLETE=1
newcommand 8>&1 9>&2 1>/dev/null 2>/dev/null
```

#### On the command line or in .cshrc:
    complete newcommand.py 'p@*@`newcommand-complete.sh`@'

**Comment by davvid** [comment]
I am not aware of any convention in `/etc` or elsewhere for tcsh
