### ISSUE TITLE
zsh escapes space after singleton completions

### ISSUE THREAD

**Issue by redstreet** [kislyuk/argcomplete#50]
On unique completion possibilities, a trailing space is added. This has the nice effect of adding a space on the command line, but is not an ideal way to do so. zsh, for instance, is smart enough to notice that trailing space, and keeps escaping it automatically (so instead of '--help', zsh completes it as '--help\ ' which is incorrect).

IMHO, this is better handled by removing the '-o nospace' in:

```
complete -o nospace -o default -F _python_argcomplete "t"
```

...and removing these lines:
#### in **init**.py:

```
 If there's only one completion, and it's not open-quoted and doesn't end with a continuation char, add a space
 continuation_chars = '=/:'
if len(completions) == 1 and completions[0][-1] not in continuation_chars:
    if cword_prequote == '' and not completions[0].endswith(' '):
        completions[0] += ' '
```

Is there any reason not to do so that I'm not seeing?

**Comment by evanunderscore** [comment]
Does it make sense to have "singleton completions that may be partial"? In the case of a directory name followed by a slash, should you not also return the contents of that directory? For example, if you return `dir/` and expect the user could use something in that directory, why not also return `dir/subdir/`, `dir/file`, etc?

**Comment by kislyuk** [comment]
Yes, it does. Try completing a path of several directories in bash. Even if there is a unique completion, each `<TAB>` will yield just one directory completion at a time. That's an intentional UX design, and I'd like to conform to it.

**Comment by kislyuk** [comment]
More generally, we can't reasonably return all completions in a tree hierarchy.

**Comment by evanunderscore** [comment]
What I had assumed was happening is that when a directory would be returned as the only match, it also returned the contents of that directory, eg `dir/` and `dir/subdir` (but not `dir/subdir/file` or any deeper in the hierarchy), which would cause `dir/` to be filled in as the common prefix. However you are correct - even when `show-all-if-ambiguous` is turned on, bash will not display the contents of a directory until tab is pushed a second time.
