### ISSUE TITLE
Need some help figuring out how to disable this

### ISSUE THREAD

**Issue by andersfylling** [kislyuk/argcomplete#501]
Hello! It seems a package on my system has enabled this for me, which I did not expect. My current case is that whenever I'm using a program and trying to auto complete some file path it jumps into argcomplete and breaks down:
![image](https://github.com/user-attachments/assets/65ff1e44-72e8-405b-9957-1dccbe32c7d1)

Any easy way to just disable this while I work on patching whatever packages caused this issue? 
This isn't really an issue with argparse(?), just hoping there's some insight in the community to help me temporarily bypass this :smile: 

Terminal is zsh flavor.

**Comment by evanunderscore** [comment]
Depending on exactly how the global completion script has been installed, you might be able to restore the default completer with `compdef _default -default-`. You'll likely have to rerun this every time you open the shell.

**Comment by kislyuk** [comment]
Hello,

It looks like you have some leftover files in your zsh completions directory from an argcomplete installation that was not deactivated before being uninstalled. You can list these files using `for i in $fpath; do ls $i/*argcomplete*; done` and remove them.
