### ISSUE TITLE
~/.bash_completion.d/python-argcomplete.sh prevents other completions

### ISSUE THREAD

**Issue by jmlopez-rod** [kislyuk/argcomplete#67]
I noticed a while ago that when I source the script `python-argcomplete.sh` I cannot tab to complete environment variables. If I comment the last line in the script:

```
#complete -o default -D -F _python_argcomplete_global
```

Then I can do:

```
macbook-pro:~ jmlopez$ echo $PA<TAB>
macbook-pro:~ jmlopez$ echo $PATH
```

As soon as I activate the global completer then it doesn't do the environment variable completion anymore. This behavior does not happen when registering an awesome script, i.e.

```
eval "$(register-python-argcomplete my-awesome-script.py)"
```

Not sure if this is happening with others, can someone check if this is  bug on argparse? I'm using bash 4.2:

```
macbook-pro:~ jmlopez$ echo $BASH_VERSION
4.2.45(2)-release
```

**Comment by jiasli** [comment]
`register-python-argcomplete` is not using `-o bashdefault` by default:

https://github.com/kislyuk/argcomplete/blob/abfa18712ec795445857f4125ed5ff3b51107f2c/argcomplete/shell_integration.py#L77

Although it can be overridden with [`--complete-arguments`](https://github.com/kislyuk/argcomplete/blob/b2a3192d6804986a4b51a0e355d5bb0cc1f7c6eb/scripts/register-python-argcomplete#L38-L41), maybe we can include `-o bashdefault` for individual command registration as well?

**Comment by evanunderscore** [comment]
Thank you for reporting @jiasli. This appears to be an oversight. Would you like to submit a PR?

**Comment by jiasli** [comment]
Sure. With pleasure!
