### ISSUE TITLE
Teach argcomplete that command subcommand calls command-subcommand

### ISSUE THREAD

**Issue by asmeurer** [kislyuk/argcomplete#76]
Is there some way to tell argcomplete that `command subcommand` for any subcommand that isn't explicitly a subparser of argparse calls out to `command-subcommand`? We use this as a plugin architecture (similar to git).

**Comment by bewest** [comment]
I have a similar issue, I'm using calling out subshells to do autocompletion: https://github.com/openaps/openaps/blob/master/bin/openaps

However, after the subprocess has done it's completion, the original wrapper is adding the top-level completion opts again, (after the last `nargs=argparse.REMAINDER` in the top level shell).  Does anyone know how to prevent that from happening?

**Comment by asmeurer** [comment]
I ended up with the following implementation, which subclasses `argcomplete.CompletionFinder` and overrides `__call__` https://github.com/conda/conda/pull/1443. I also implement calling it automatically inside of a custom subclass of ArgumentParser, so that extensions only have to import and use that custom subclass to get completion.
