### ISSUE TITLE
completion with non-dash-options (positionals)

### ISSUE THREAD

**Issue by felskrone** [kislyuk/argcomplete#84]
I trying to write a script with various sub-commands that execute different actions. For example remote managing a server and debugging connectivity isssues or enable/disable services.

```bash
   server
       - test                 # sub-command 1
           - ping            # sub-sub-command 1.1
           - mtr             # sub-sub-command 1.2
       - config             # sub-command 2
           - apache       # sub-sub-commands 2.1
               - enable    # sub-sub-sub-commands 2.1.1
               - disable   # sub-sub-sub-command 2.1.2
```

What i would like to have is the auto-completion of all sub-*-commands so a user does not have to know all the sub-commands by heart. 

Example usage woud be:

```bash
    server<space><TAB>
    test config            # auto-completion prints available sub-commands
    server test<space><TAB>
    ping mtr               # autocompletion prints test-sub-commands
    server test ping <servername>
```

The sub-commands shall not start with dashes as they are not actual switches. I guessing this could be done with a custom completer? So far i could not get argcomplete to auto-complete anything that has no dashes in it.

Can this be done with argcomplete?

**Comment by shehzadi** [comment]
I'm seeing the same problem. Default does not work for options without dashes.

**Comment by kislyuk** [comment]
Thanks for the report. Can you please paste a test use case that you expect to work?

**Comment by shehzadi** [comment]
Thank you for the quick response. I got it working. If you add the argument to the main parser like in the following snippet it does **not** work:

```
parser = argparse.ArgumentParser(description='description')
parser.add_argument("option", dest="option", help="positional option help")
argcomplete.autocomplete(parser)
args = parser.parse_args()
```

If you add the argument as a subparser then the code works as intended. Example snippet:

```
parser = argparse.ArgumentParser(description='description')
subparsers = parser.add_subparsers()
parser_option = subparsers.add_parser("option", help="positional option help")
parser_option.add_argument("--optional_option", dest="optional_option", help="optional option under option help")
argcomplete.autocomplete(parser)
args = parser.parse_args()
```

I was expecting argcomplete to work with the first snippet. Hope that help :+1:

**Comment by wapiflapi** [comment]
Argcomplete can not possibly know what the possible values are in the first case.
If you specify the possible option choices like follows the first method should also work: 
```
parser.add_argument('move', choices=['rock', 'paper', 'scissors'])
```

The second option is however the preferred way to achieve this result in my opinion.

**Comment by shehzadi** [comment]
The confusion arises from the fact that this works:

```
parser = argparse.ArgumentParser(description='description')
parser.add_argument("--option", dest="option", help="optional option help")
argcomplete.autocomplete(parser)
args = parser.parse_args()
```

but this does not:
```
parser = argparse.ArgumentParser(description='description')
parser.add_argument("option", dest="option", help="positional option help")
argcomplete.autocomplete(parser)
args = parser.parse_args()
```

A positional argument may not necessarily have "choices". So if there were no choices I would still have to create a subparser to autocomplete the positional argument. That, to me, is less intuitive. Following demonstrates how to autocomplete a positional argument that doesn't have "choices"
```
parser = argparse.ArgumentParser(description='description')
subparsers = parser.add_subparsers()
parser_option = subparsers.add_parser("option", help="positional option help")
argcomplete.autocomplete(parser)
args = parser.parse_args()
```

**Comment by wapiflapi** [comment]
Your last example does have 'choices'. The only valid thing a user can type is literally ```option``` because that is the name of your subparser. This can be easily visualized by running the example and letting argparse do its job:

```
$ python test.py 
usage: test.py [-h] {option} ...
test.py: error: too few arguments

$ python test.py foobar
usage: test.py [-h] {option} ...
test.py: error: invalid choice: 'foobar' (choose from 'option')
```

In general you can't expect argcomplete to complete stuff that it doesn't know the valid values for. In the first example the only valid value is ```---option``` in the third it's ```option```. But the positional argument in the second example will accept any user-supplied value and therefor can't be completed.

**Comment by shehzadi** [comment]
I would suggest an explicit mention for that in the doc.

**Comment by kislyuk** [comment]
@shehzadi, I think you're a bit confused about how argparse works. The rule of thumb for argcomplete is that it won't generate an invalid completion (one that causes the argparse parser to throw an error). If we were to complete anything on a positional that we don't have any choices information for, the completions would not be valid (to our best knowledge, anyway). There is nothing to complete on a positional with no completion information. However, once you declare a subparser, we do have the ability to complete on the subparser name.

The main thing you need to do is just look at the form of arguments that you supply to your program, and look at how you can inform argcomplete about what to suggest at any point in the command line.

Ultimately, what you might be looking for is out-of-band help information for completions: in other words, in addition to suggesting completions to your command line, the tab completion driver would also print - not into the command line! - help information for the option currently under the cursor. I know Zsh has this capability, but unfortunately I'm not aware of any way for bash to support it (though perhaps I could try printing to stderr).

If you have any specific wording for a warning that you want me to insert into the doc (including examples), please feel free to paste it here.

**Comment by kislyuk** [comment]
@felskrone, please let us know if the discussion (and examples with the "choices" parameters) above also answer your questions.

**Comment by gnydick** [comment]
Yeah, this would be good if the positionals were autocompleted like

<code>
foocommand foosubcommand foosubsubcommand {positional_param_1} {positional_param_2}
</code
that seems ultimately reasonable

**Comment by evanunderscore** [comment]
@gnydick The consensus from this discussion is that completion of subcommands works if your argument parser is built using subparsers. If you're not able to get this working the way you want, please open a new issue and include a code example.
