### ISSUE TITLE
debug mode should not mute output

### ISSUE THREAD

**Issue by asmeurer** [kislyuk/argcomplete#97]
Debug mode shouldn't mute the output, especially stderr. Usually when I get things wrong, it's because some traceback is raised (e.g., an AttributeError in the parsed_args argument of the completer). 

I tried disabling the muting in debug mode, but it didn't work. I'm not sure what I was doing wrong.

**Comment by evanunderscore** [comment]
I agree, this would be very helpful.

The standard streams are redirected to /dev/null in the the shell scripts, so I'm not sure what the `mute_*` decorators are meant to be used for.
